### ISSUE TITLE
F as a function name

### ISSUE THREAD

**Issue by matthewross07** [SebKrantz/collapse#100]
First, thank you so much for this really nice package. This is not your issue so much as it is mine and other bad syntax programmers like me, of which I think there are many. 

In Collapse there is a function F(), but if you have poor programming practice like myself you frequently get lazy and set a statement to T/F instead of TRUE/FALSE as you technically should. As a result when collapse is loaded any function that has this lazy F will throw up errors. 

Though it's probably not best to enable my bad practices, I think it's an obscure enough error that many people will get tripped up on this problem. Maybe consider changing?

Either way, really love this package and thank you again.

**Comment by SebKrantz** [comment]
Hello, thanks for bringing this up. Haven’t thought about this. I think there could be more issues with T and F in collapse though. As collapse is geared towards speed, I rarely use isTRUE and isFALSE, and in some cases where arguments allow both TRUE, FALSE or  other options specified as characters strings, this is implemented using a switch i.e. switch(arg, TRUE = ..., FALSE = ..., bla = ..., ...). switches always match on the character content. Also I‘m hesitant doing such namespace changes at this point, I want to keep the package as stable as possible. So thanks again for flagging this, bot I don’t think I will do something about it.

**Comment by matthewross07** [comment]
That seems reasonable to me. Maybe just a warning when loading the package? 

Thanks again and totally understand not shifting for those of us with bad practices :-)

**Comment by SebKrantz** [comment]
Hello, I have thought about this, but I don't want to put any more things in the package startup message. I'm afraid there is not much I can do here. An easy remedy for code suffering from this seems however to just create a variable `F <- FALSE` at the top of the script.
