### ISSUE TITLE
use fixest to replace lfe

### ISSUE THREAD

**Issue by waynelapierre** [SebKrantz/collapse#102]
Do you have any plans to replace collapse's dependency on lfe with fixest? lfe is slow and seems to lack proper maintenance. Meanwhile, fixest is fast and well maintained.  

Thanks again for your great package. I am working on a research project using high-frequency foreign exchange data, which is a huge panel data. Your package's qsu function really makes my life much easier.

**Comment by SebKrantz** [comment]
Hey, yes I have already implemented the fixest backend. I can probably push the development version to Github by the end of this weekend. It will then be on CRAN by January.

**Comment by SebKrantz** [comment]
So the fixest backend is now there in the development branch. You can install collapse 1.5.0 using `remotes::install_github("SebKrantz/collapse", "development")`. Feel free to give feedback.
