### ISSUE TITLE
Vignettes 

### ISSUE THREAD

**Issue by helix123** [SebKrantz/collapse#119]
I noticed the Vignettes were removed from the package and outsourced to a website due to their size.

Maybe you want to put a placeholder vignette linking to the vignettes on the website so that on collapse's CRAN page the Vignette field has an entry point to the real Vignettes? The Vignettes are incredibly helpful and well written. I suspect people might oversee them, esp. when they evaluate the CRAN webpage of collapse.

**Comment by SebKrantz** [comment]
Thanks, It’s a good idea. I‘ll do it for the next release.
