### ISSUE TITLE
Speed up plm::pmg with collapse 

### ISSUE THREAD

**Issue by lyifa** [SebKrantz/collapse#120]
I have a large panel data that I need to use the plm::pmg function. The pmg function is pretty slow for my data. Does using your collapse package make the pmg functions faster?

**Comment by helix123** [comment]
See the development version of package `plm`, powered by `collapse`: https://r-forge.r-project.org/R/?group_id=406
Be sure to enable fast mode by setting an option: `options("plm.fast" = TRUE)`.

**Comment by waynelapierre** [comment]
Why not plm make plm.fast = TRUE as the default option?

**Comment by SebKrantz** [comment]
So these things will be sorted as `plm` integrates more closely with `collapse`. For the moment we are very careful not to break any `plm` code, so we will first make the acceleration optional and eventually make it a default option. If `plm` gets a Github repo it will be good to flag such issues there.

**Comment by tappek** [comment]
The `pmg` function in package `plm` should be faster in usual mode as well as in "fast mode" with the new CRAN release of plm version 2.4-2 - the release notes https://cran.r-project.org/web/packages/plm/news/news.html

(Apologies for posting to the collapse repo (and even a closed topic) once again for a plm-related topic!)
