### ISSUE TITLE
Argument checking

### ISSUE THREAD

**Issue by tappek** [SebKrantz/collapse#125]
As I saw you put quite some effort into checking of input arguments! I thought a leave a tiny hint for further improvement shall you be interested.
The fine error output for the commands below specify what is expected, but not for which argument; the second case with `= NULL`  I found harder to track down as it was not clear to me it refers to arguments.

Anyways, looking at the fine documentation, it is very clear.

```
library(collapse)
data(wlddev, package = "collapse")
collapse::fbetween(wlddev$PCGDP, g = wlddev$iso3c, w = NULL, na.rm = "a") 
# Error in fbetween.default(wlddev$PCGDP, g = wlddev$iso3c, w = NULL, na.rm = "a") : 
#   Not compatible with requested type: [type=character; target=logical].
collapse::fbetween(wlddev$PCGDP, g = wlddev$iso3c, w = NULL, na.rm = NULL)
#Error in fbetween.default(wlddev$PCGDP, g = wlddev$iso3c, w = NULL, na.rm = NULL) : 
#  Expecting a single value: [extent=0].
```

**Comment by SebKrantz** [comment]
Hi, thank you! These error messages are automatically generated by Rcpp when an input of the wrong type is passed to a C++ function. Most of my checks are run at C++ level, but If you pass inputs of the wrong data type you get a generated message like that, which I cannot modify. I don't think I'll add some manual checks in R as they are costly and not necessary in my opinion, particularly not for standard arguments like `na.rm`.
