### ISSUE TITLE
Links in online documentation which are "Page not found (404)"

### ISSUE THREAD

**Issue by Henrik-P** [SebKrantz/collapse#126]
First, thanks a lot for your great work!

I was browsing through the nice online documentation and stumbled on some links that need to be updated (Page not found (404)).

Site:
https://sebkrantz.github.io/collapse/reference/fast-statistical-functions.html
Page not found:
[Data Transformations](https://sebkrantz.github.io/collapse/reference/A6-data-transformations.html)
[Time Series and Panel Series](https://sebkrantz.github.io/collapse/reference/A7-time-series-panel-series.html)

Sites:
https://sebkrantz.github.io/collapse/reference/fmean.html
https://sebkrantz.github.io/collapse/reference/fmedian.html
https://sebkrantz.github.io/collapse/reference/fmode.html
https://sebkrantz.github.io/collapse/reference/fsum.html
https://sebkrantz.github.io/collapse/reference/fprod.html
https://sebkrantz.github.io/collapse/reference/fvar_fsd.html
https://sebkrantz.github.io/collapse/reference/fmin_fmax.html
https://sebkrantz.github.io/collapse/reference/fnth.html
https://sebkrantz.github.io/collapse/reference/ffirst_flast.html
https://sebkrantz.github.io/collapse/reference/fNobs.html
https://sebkrantz.github.io/collapse/reference/fNdistinct.html
https://sebkrantz.github.io/collapse/reference/collap.html
https://sebkrantz.github.io/collapse/reference/data-transformations.html
https://sebkrantz.github.io/collapse/reference/summary-statistics.html
https://sebkrantz.github.io/collapse/reference/qsu.html
https://sebkrantz.github.io/collapse/reference/collapse-options.html
Page not found:
[Fast Statistical Functions](https://sebkrantz.github.io/collapse/reference/A1-fast-statistical-functions.html)

Site:
https://sebkrantz.github.io/collapse/reference/fast-grouping.html
Page not found:
[Data Frame Manipulation](https://sebkrantz.github.io/collapse/reference/A3-fast-data-manipulation.html)
[Fast Statistical Functions](https://sebkrantz.github.io/collapse/reference/A1-fast-statistical-functions.html)

Sites:
https://sebkrantz.github.io/collapse/reference/GRP.html
https://sebkrantz.github.io/collapse/reference/radixorder.html
https://sebkrantz.github.io/collapse/reference/funique.html
https://sebkrantz.github.io/collapse/reference/qF.html
https://sebkrantz.github.io/collapse/reference/fdroplevels.html
https://sebkrantz.github.io/collapse/reference/groupid.html
https://sebkrantz.github.io/collapse/reference/seqid.html
https://sebkrantz.github.io/collapse/reference/roworder.html
https://sebkrantz.github.io/collapse/reference/qF.html
Page not found:
[Fast Grouping and Ordering](https://sebkrantz.github.io/collapse/reference/A2-fast-grouping-ordering.html)

Site:
https://sebkrantz.github.io/collapse/reference/fast-data-manipulation.html
Page not found:
[Quick Data Conversion](https://sebkrantz.github.io/collapse/reference/A4-quick-conversion.html)
[Recode and Replace Values](https://sebkrantz.github.io/collapse/reference/AA1-recode-replace.html)

Site:
https://sebkrantz.github.io/collapse/reference/select_replace_vars.html
https://sebkrantz.github.io/collapse/reference/fsubset.html
https://sebkrantz.github.io/collapse/reference/ftransform.html
https://sebkrantz.github.io/collapse/reference/colorder.html
https://sebkrantz.github.io/collapse/reference/frename.html
Page not found:
[Data Frame Manipulation](https://sebkrantz.github.io/collapse/reference/A3-fast-data-manipulation.html)

Site:
https://sebkrantz.github.io/collapse/reference/data-transformations.html
https://sebkrantz.github.io/collapse/reference/fdiff.html
https://sebkrantz.github.io/collapse/reference/fgrowth.html
https://sebkrantz.github.io/collapse/reference/psacf.html
Page not found:
[Time Series and Panel Series](https://sebkrantz.github.io/collapse/reference/A7-time-series-panel-series.html)

Site:
https://sebkrantz.github.io/collapse/reference/arithmetic.html
https://sebkrantz.github.io/collapse/reference/fbetween_fwithin.html
https://sebkrantz.github.io/collapse/reference/fHDbetween_fHDwithin.html
https://sebkrantz.github.io/collapse/reference/flm.html
https://sebkrantz.github.io/collapse/reference/fFtest.html
https://sebkrantz.github.io/collapse/reference/time-series-panel-series.html
Page not found:
[Data Transformations](https://sebkrantz.github.io/collapse/reference/A6-data-transformations.html)

Site:
https://sebkrantz.github.io/collapse/reference/dapply.html
https://sebkrantz.github.io/collapse/reference/BY.html
https://sebkrantz.github.io/collapse/reference/TRA.html
https://sebkrantz.github.io/collapse/reference/fscale.html
Page not found:
[Fast Statistical Functions](https://sebkrantz.github.io/collapse/reference/A1-fast-statistical-functions.html)
[Data Transformations](https://sebkrantz.github.io/collapse/reference/A6-data-transformations.html)

Site:
https://sebkrantz.github.io/collapse/reference/flag.html
Page not found:
[Fast Statistical Functions](https://sebkrantz.github.io/collapse/reference/A1-fast-statistical-functions.html)
[Time Series and Panel Series](https://sebkrantz.github.io/collapse/reference/A7-time-series-panel-series.html)

Site:
https://sebkrantz.github.io/collapse/reference/is.unlistable.html
https://sebkrantz.github.io/collapse/reference/ldepth.html
https://sebkrantz.github.io/collapse/reference/extract_list.html
https://sebkrantz.github.io/collapse/reference/rsplit.html
https://sebkrantz.github.io/collapse/reference/rapply2d.html
https://sebkrantz.github.io/collapse/reference/unlist2d.html
Page not found:
[List Processing](https://sebkrantz.github.io/collapse/reference/A8-list-processing.html)

Site:
https://sebkrantz.github.io/collapse/reference/qsu.html
Page not found:
[Fast Statistical Functions](https://sebkrantz.github.io/collapse/reference/A1-fast-statistical-functions.html)
[Summary Statistics](https://sebkrantz.github.io/collapse/reference/A9-summary-statistics.html)

Site:
https://sebkrantz.github.io/collapse/reference/pwcor_pwcov_pwNobs.html
Page not found:
[Summary Statistics](https://sebkrantz.github.io/collapse/reference/A9-summary-statistics.html)

Site:
https://sebkrantz.github.io/collapse/reference/varying.html
Page not found:
[Data Transformations](https://sebkrantz.github.io/collapse/reference/A6-data-transformations.html)
[Summary Statistics](https://sebkrantz.github.io/collapse/reference/A9-summary-statistics.html)

Site:
https://sebkrantz.github.io/collapse/reference/recode-replace.html
Page not found:
[Small (Helper) Functions](https://sebkrantz.github.io/collapse/reference/AA2-small-helpers.html)

Cheers

**Comment by SebKrantz** [comment]
Thanks a lot! I am aware of this, and it seems to be related to a bug in `pkgdown` which causes it to not properly process my top-level documentation pages (with names starting with A1-, A2- etc.). You can see that the working links to these pages have the AX- prefix removed, whereas the links that don't work have the prefix. I can try to manually do some search and replace in the generated HTML files to fix this, but on the face of it it's a `pkgdown` error which will hopefully be fixed soon.

**Comment by SebKrantz** [comment]
This is fixed now on the website using a ctrl+F search and replace in the generated HTML files. Still hoping for this to be fixed in a `pkgdown` update.
