### ISSUE TITLE
is.regular

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#127]
`is.regular` conflicts with the generic of the same name in zoo which checks whether its argument is regularly spaced.  Note that collapse claims to be compatible with zoo.

**Comment by SebKrantz** [comment]
Thanks, collapse claims to non-destructively manipulate zoo objects, not full compatibility with the namespace. But `is.regular` is indeed not a very useful function and could be removed from the package. I'll think about it. In any case it would have to be phased out and that would take at least half a year given the careful approach I want to take regarding lifecycle management.
