### ISSUE TITLE
num_vars, cat_vars and columns that are all NA

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#128]
If a column in a data frame is all NA then you have to be very careful to use NA_real_ or NA_integer_ when setting it if you want it fetched using num_vars and not when using cat_vars.  

One idea is to raise a warning if there are any logical columns containing all NA or perhaps just put a warning in the help file.

**Comment by SebKrantz** [comment]
Thank you, I am however not sure if this is something requiring a change, a NA is a logical constant in R so it should be in cat_vars. Fundamentally num_vars and cat_vars do the same thing as data[sapply(data, is.numeric)] and data[!sapply(data, is.numeric)] In a more efficient way (using vapply and list-subsetting). I don’t want to do something that behaves fundamentally different from base R. I also note that you have the fNobs and varying functions in collapse that let you easily detect and remove such columns.
