### ISSUE TITLE
selecting one column

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#139]
Using the built-in `anscombe` data frame, the following gives an error:

```
> slt(anscombe, 2)
Error in slt(anscombe, 2) : Unknown columns: 2

> ss(anscombe, , 2)
Error in ss(anscombe, , 2) : argument "i" is missing, with no default

> ss(anscombe, TRUE, 2)
Error in ss(anscombe, TRUE, 2) : 
  i needs to be integer or logical(nrow(x))

```

although, these work:

```
slt(anscombe, x2)  # second column is named x2
slt(anscombe, 2:2) # second column
slt(anscombe, 1:2) # first two columns
```

**Comment by SebKrantz** [comment]
Hi, so again I think you need to read the documentation better. `fselect / slt` is for NSE, It converts columns entered without quotes to integers, which are used to subset the data. It will also work if you enter plain integers, but not doubles, but you should not be using `fselect / slt` with integers or other standard evaluation expressions. There is another function called `get_vars / gv / gvr` , which is actually documented on the same page. That one may be used to flexibly select columns with column names, indices (integer or double), logical vectors regular expressions or a function that is applied to all columns and returns `TRUE` or `FALSE`. So this is the function you want. Now for subsetting rows (and columns), there is a NSE function `fsubset / sbt`, and a standard evaluation function `ss`. You cannot use these functions to only select columns, you can use them to subset rows, (optionally) on selected columns.

**Comment by ggrothendieck** [comment]
Perhaps closer reading would resolve this but it is highly confusing.  There are so many functions and the operation here is not what one would expect.

**Comment by SebKrantz** [comment]
Agreed, dplyr makes things simple as it allows you to do NSE and standard
eval in one function, but the mechanics of that are highly complex (see the
Advanced R book section on NSE with rlang), and executions speeds quite
slow. collapse provides you separate functions for NSE and SE i.e. mutate
-> fselect or get_vars and filter -> fsubset or ss. What is confusing here
is that you can abbreviate some of these functions. That’s just a tribute
to my laziness and other software like STATA where you can abbreviate
commands. But that should not confuse you, the only thing you need to keep
in mind is that you don’t do NSE and SE with the same function in collapse.

**Comment by ggrothendieck** [comment]
Maybe if the function naming were more regular it would reduce the cognitive load in learning this. 

If get_vars and fselect are the same except for NSE/standard eval one has to remember two different function names.  Maybe if there were fselect and fselect_ with an underscore with one being NSE and the other standard evaluation and similarly for other functions it would be easier to remember.

I still don't understand why 2:2 worked but 2 did not.

**Comment by SebKrantz** [comment]
Yeah, I agree, it’s because NSE functions like fselect were only added
later, initially collapse was only SE and there was only get_vars. I
suggest just giving help(„collapse-documentation“) a careful read through,
then you’ll more or less know what every function does. I won’t make the
naming more consistent, I want the API to be stable and reliable. 2:2
worked because the result is integer. 2 is double, 2L is integer and will
also work. But again use get_vars.

**Comment by ggrothendieck** [comment]
That is pretty subtle. I don't know of any other R software that distinguishes between integer and double for indexes.  If that was mentioned anywhere I certainly missed it.

**Comment by SebKrantz** [comment]
It should also give an error for the integers, as fselect is supposed to
take only column names entered without quotes, that I believe you can take
from the documentation. Checking whether an expression is integer before it
is evaluated is complex, and that error message will not be implemented.
Bottom line: collapse is simple, stable and fast, nothing more, nothing
less.

**Comment by ggrothendieck** [comment]
It is very fast but the user interface is not simple -- there are many functions, they don't have consistent naming,, they act in unexpected ways not always consistent with the rest of R and you have to read the documentation very carefully to understand them and even then may miss important points.

**Comment by SebKrantz** [comment]
Thanks, I appreciate the feedback I must say. I‘ll think about what I can
do. I think there are just a few too many objectives I tried to target with
it such as namespace compatibility and support for both dplyr and
data.table, speed, code simplicity and a bit of my own liking.

**Comment by ggrothendieck** [comment]
I don't understand it well enough to fully comprehend it yet but it might be that if one sticks to the standard evaluation functions that one can avoid any problems.  Nonstandard evaluation was initially discouraged in the R community but then tidyverse used it and when they realized the problem that got them into the rabbit hole of rlang.   At any rate I am using collapse nearly every day right now but I still am using just a handful of functions. I am sure I will figure out which are SE and which are NSE over time and I may stick with the SE versions for which I expect there will be no problem at all or else I may jjust deal with it as is as I become more comfortable with the various functions in the package.

**Comment by SebKrantz** [comment]
So I don't think there is necessarily a problem with NSE in collapse, it's just that NSE is simple like base R NSE (in functions with(), subset(), transform() etc.). What rlang lets you do is have NSE functions take standard evaluation arguments (through stuff like quosures etc.). None of this is implemented in collapse. The NSE functions in collapse currently are: fselect, fsubset, ftransform, settransform, fgroup_by, fummarise, collapg. roworder, colorder, frename, setrename. Just if you use those functions don't pass any vectors or objects you want to be evaluated in a standard way. That's it really.

**Comment by ggrothendieck** [comment]
Thanks.  That list should be useful in getting my head around this.

**Comment by ggrothendieck** [comment]
Are there also standard evaluation versions of fselect, fsubset, ftransform, settransform, fgroup_by, fummarise, collapg, roworder, colorder, frename, setrename?  I understand that get_vars is the SE version of fselect.

**Comment by SebKrantz** [comment]
Apart from fsummarise and fgroup_by, yes. Please read
help(.COLLAPSE_TOPICS[4]) and the help pages linked there.

**Comment by ggrothendieck** [comment]
The BY documentation says it is " principally a wrapper around lapply(split(x, g), FUN, ...)," but it seems it is not sending the same thing as lapply(split(...), ...) to the function.  What is happening here?

```
eaten <- structure(list(person = c("Grace", "Grace", "Grace", "Rob", "Rob", 
"Rob"), foods = c("apple", "banana", "cucumber", "spaghetti", 
"cucumber", "banana")), class = "data.frame", row.names = c(NA, 
-6L))
eaten <- structure(list(person = c("Grace", "Grace", "Grace", "Rob", "Rob", 
"Rob"), foods = c("apple", "banana", "cucumber", "spaghetti", 
"cucumber", "banana")), class = "data.frame", row.names = c(NA, 
-6L))

combos <- function(x) combn(x$foods, m = 2)

lapply(split(eaten, eaten$person), combos)
## $Grace
##      [,1]     [,2]       [,3]      
## [1,] "apple"  "apple"    "banana"  
## [2,] "banana" "cucumber" "cucumber"
##
## $Rob
##      [,1]        [,2]        [,3]      
## [1,] "spaghetti" "spaghetti" "cucumber"
## [2,] "cucumber"  "banana"    "banana"  

BY(eaten, eaten$person, , return = "list")
## Error: $ operator is invalid for atomic vectors
```

**Comment by SebKrantz** [comment]
BY.data.frame works as `lapply(data, function(x) lapply(split(x, g), FUN, ...))` which is substantially faster than splitting the whole frame. The description says `BY is an S3 generic that efficiently applies functions over vectors or matrix- and data frame columns by groups. `, so it applies to the columns, not the whole frame, and yes it also wraps `lapply(split(x, g), FUN, ...)`. Maybe I should put it clearer, but I think the examples also make it clear.

**Comment by ggrothendieck** [comment]
If both BY and collap work column by column by group they seem very similar.

**Comment by SebKrantz** [comment]
BY is used internally by collap() if you pass a function other than a Fast
Statistical Function to collap(). In fact BY() is the only function in the
whole package that does basic split-apply-combine computing. Otherwise this
package is totally beyond split-apply-combine, using one-pass grouped
computations in C++ loops.
