### ISSUE TITLE
speed of fsd

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#141]
I tried benchmarking fsd and sd ran faster.

```
> library(microbenchmark)
> x <- 1:1e6
> microbenchmark(sd = sd(x), fsd = fsd(x))
Unit: milliseconds
 expr     min       lq     mean   median       uq      max neval cld
   sd 17.2881 19.88775 24.05444 20.87300 21.86765  69.5896   100  a 
  fsd 28.5483 30.28625 41.80759 31.44415 32.15310 489.9944   100   b
```

**Comment by SebKrantz** [comment]
You have a faster option `fsd(x, stable.algo = FALSE)` which only causes numeric problems if you have large data (many obs), large values and a small sd between those values. `fsd` is also equal speed with doubles (I think `sd` has a built-in method for integers which is more efficient), and certainly faster for real world data with missing values. In general, Fast Statistical Functions have the default `na.rm = TRUE`, and (apart from fmode, ffirst and flast, fNobs and fNdistinct) don't have separate integer methods (thus integer input is coerced to double). They are optimized for computing with missing values, and grouped computations. They are slao S3 generic so there is a overhead to the method dispatch. So with the exception of `fmean` and `fmedian`, you should use primitive base functions `sum`, `min` and `max` for computations on integers and stylized computations inside programs.
