### ISSUE TITLE
Support `fgroup_by()` with `character` names

### ISSUE THREAD

**Issue by psychelzh** [SebKrantz/collapse#142]
In programming, it is very often that the grouping variables are stored as a character, but currently, this seems incompatible with `fgroup_by()`.

**Comment by SebKrantz** [comment]
Thanks, yes I‘m thinking about doing that for the next release. Note however that collapse provides advanced and flexible alternative mechanisms for programming in standard evaluation. See ?GRP. Those dplyr-like functions are just jargon for people coming from that end who want to speed up existing dplyr code. You can also create a grouped data frame using 

data %>% structure(groups = GRP(., vars), class = c(„GRP_df“, „grouped_df“, class(.)))

**Comment by psychelzh** [comment]
Thank you very for your quick answer. I will also try to use other programming methods using standard evaluation.

**Comment by psychelzh** [comment]
I think [this article](https://dplyr.tidyverse.org/articles/programming.html) of dplyr is easy to understand the NSE and SE. If this package follow the same logic there, life will be better.

**Comment by SebKrantz** [comment]
Thanks, but dplyr depends on rlang and there is a whole host of complex
code to make that happen. Collapse is dependency free and lightning fast,
built only with base R and Rcpp. I will see what can be done with base R
about your request, but collapse will never depend on rlang.

**Comment by psychelzh** [comment]
That is great. Less dependency is great feature for this package. Many thanks for developing this package!

**Comment by SebKrantz** [comment]
This is now fixed, programming with fgroup_by is enabled. You can already install the development version from Github to access this feature, CRAN release will be in about 2 weeks time.
