### ISSUE TITLE
`add_vars()<-` should support specify the name all the new column

### ISSUE THREAD

**Issue by psychelzh** [SebKrantz/collapse#143]
Surprisingly, I cannot specify the column name for the added variable in `add_vars()<-`. Currently, `ftransform()` can do this, but no standard evaluation is supported. It turned out that I use the base `[<-`, again. Hopefully, programming using this package will be better soon.

**Comment by SebKrantz** [comment]
You can use add_vars() <- list(newcol = ...). Please provide reproducible examples for your issues.

**Comment by psychelzh** [comment]
Oh, thank you very much. This should be my fault.

**Comment by psychelzh** [comment]
BTW, can I rename the generated variables from `collapv()`? Currently I am using `setNames()` instead.

**Comment by SebKrantz** [comment]
No, collap is for aggregating many variables,  but there is fsummarise.

**Comment by psychelzh** [comment]
Here it goes the issue of programming with `fsummarise()`. :(

**Comment by SebKrantz** [comment]
Ok, but then I don’t understand how you would want to do it. If you don’t want to code interactively like newname = something, how are you going to go without setting names in the classical way?

**Comment by psychelzh** [comment]
Maybe I have managed to do programming in the "dplyr" framework so I am expecting this. Another issue is that it is clearer for me to think of aggregating while creating the new variable names at the same time, which is not easy to treat these as two separating steps. It is a bonus eventually, but will make life better for me a lot.

**Comment by SebKrantz** [comment]
Ok, if you give a concrete example of how you‘d do it in dplyr, I can think about it. What collap facilitates which I am missing in dplyr is the idea of crunching large datasets assigning different functions to many different variables and using weights for some variables. That’s why the command was created. Regarding programming, I prefer fast programs written using primitive base functions.

**Comment by psychelzh** [comment]
What I know is that dplyr uses a pronoun `.data` to achieve programming, see the following. Hope it will help.

``` r
library(tidyverse)
data <- tibble(id = rep(1:2, each = 50), x = 1:100)
data %>% 
    group_by(.data[["id"]]) %>% 
    summarise(mean_x = mean(.data[["x"]]))
#> # A tibble: 2 x 2
#>      id mean_x
#>   <int>  <dbl>
#> 1     1   25.5
#> 2     2   75.5
```

<sup>Created on 2021-03-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by SebKrantz** [comment]
Ok, thanks I‘ll think about it.

**Comment by psychelzh** [comment]
Thank you for your attention on this, again. Unfortunately, this `.data` pronoun is exported from "rlang" package. :(

**Comment by SebKrantz** [comment]
Hi, so regarding this. What you are doing there with `summarise` actually works: 

``` r
  library(collapse)
  library(magrittr)

mtcars %>% 
  structure(groups = GRP(., "cyl"), # I'll try to have this work with fgroup_by in the next release
            class = c("grouped_df", class(.))) %>% # should do c("GRP_df", "grouped_df", class(.)) if you want to print it
  fsummarise(bla = fmean(.[["mpg"]]))
#>   cyl      bla
#> 1   4 26.66364
#> 2   6 19.74286
#> 3   8 15.10000

# Standard eval:
g <- GRP(mtcars, "cyl")
add_vars(g$groups, fmean(get_vars(mtcars, "mpg"), g))
#>   cyl      mpg
#> 1   4 26.66364
#> 2   6 19.74286
#> 3   8 15.10000

# ... is more flexible when it comes to performance. 
g <- GRP(mtcars, "cyl", return.groups = FALSE, call = FALSE)
fmean(get_vars(mtcars, "mpg"), g, use.g.names = FALSE)
#>        mpg
#> 1 26.66364
#> 2 19.74286
#> 3 15.10000
```

<sup>Created on 2021-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Below I also put some examples using standard eval. This approach is much more flexible as it allows you to call functions with minimal overhead, compute only what you need, i.e. in the second example I don't use the unique groups so I don't compute them and also omit a call to `match.call()` as well as the row names in the aggregated data frame. Forther advantages are that you can compute on arbitrary objects such as matrices (which are generally faster than data-frame' if statistics is what you are doing). and finally you can reuse the grouping `g` as many times as you want with different functions. So this API is actually much lower level, it lets you create your own aggregation commands and much more. See [here](<https://sebkrantz.github.io/Rblog/2020/09/13/programming-with-collapse/>) for furtehr guidance. For `collap`, I will try to implement something like `collapv(data, id, custom = list(fmean = c(name = var))) in the next relese.

**Comment by psychelzh** [comment]
Oh, thank you very much. Actually, this syntax of `collapv(data, id, custom = list(fmean = c(name = var)))` is just what I want to file an issue to request. That is very great. 💯
