### ISSUE TITLE
Run collap() on data frame without observations

### ISSUE THREAD

**Issue by ProsiDecon** [SebKrantz/collapse#160]
Hi Sebastian, hi everyone,

First let me congratulate you to this great and very useful tool. I am using the collap() command in a shiny app. In this context, I am occasionally passing data frames with zero rows to collap() (e.g. due to previous filters). This leads to R crashing immediately. Although a dim() check on data frames passed to collap() easily circumvents the issue, it might be useful to incorporate this dim() check into the command itself, i.e. when receiving 
`collap(data, var1 + var2 ~ var3 + var4, FUN = fsum)`
with
`dim(data)[1] == 0`
return a data frame with var1 -- var4 but zero rows (e.g. through dplyr's select() or even base R). 

If I am overlooking an obvious mistake on my behalf, I am happy for suggestions.

Best,
Daniel

**Comment by SebKrantz** [comment]
Thanks for pointing this out, I can make an informative error, running a variable selection in an empty data frame is too complicated and costly, as my primary concern with this package is efficiency on both the R and C++ side of things.

**Comment by SebKrantz** [comment]
Actually this error is also an error with the statistical functions when passed an empty data frame. I'll do C++ error in all the statistical functions as well.
