### ISSUE TITLE
collap with one LHS and multiple functions

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#185]
The columns for give.name = TRUE (the default) is of the form functionName.columnName as in first example below.  We can use `give.name = FALSE` but that gives the column name for both columns as in second example.  What I actually wanted in this situation was the function name for each column instead of using the column name twice.  Suggest some way to specify that.

```
collap(anscombe, y4 ~ x4, c(fmean, fsum), keep.col.order = FALSE, give.name = TRUE)
##   x4 fmean.y4 fsum.y4
## 1  8    7.001   70.01
## 2 19   12.500   12.50


collap(anscombe, y4 ~ x4, c(fmean, fsum), keep.col.order = FALSE, give.name = FALSE)
##   x4     y4    y4
## 1  8  7.001 70.01
## 2 19 12.500 12.50
```

**Comment by SebKrantz** [comment]
Thanks! I'll see what can be done about this.

**Comment by SebKrantz** [comment]
This is implemented in the next release, to come out shortly. Exactly in the way you suggested. Thanks again.
