### ISSUE TITLE
`collapse::collap()` returns unexpected output over logical columns, but only in some cases

### ISSUE THREAD

**Issue by emmansh** [SebKrantz/collapse#188]
I get unexpected results when using `collapse::collap()` over logical data.frame columns.

### Scenario A -- working as expected
``` r
library(collapse)
#> collapse 1.6.5, see ?`collapse-package` or ?`collapse-documentation`
#> Note: stats::D  ->  D.expression, D.call, D.name
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D

df_binary <-
  data.frame(col_animal = rep(c("cat", "dog"), each = 3),
           col_a = c(1, 1, 0, 0, 0, 0),
           col_b = c(0, 0, 0, 1, 1, 0))

collap_output_df_binary <- collapse::collap(df_binary, by = ~col_animal, FUN = any)
#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

# to avoid the warning, let's repeat the collap() procedure, but convert data as logical first
df_logical <- df_binary
df_logical$col_a <- as.logical(df_logical$col_a)
df_logical$col_b <- as.logical(df_logical$col_b)

collap_output_df_logical <- collapse::collap(df_logical, by = ~col_animal, FUN = any)


identical(collap_output_df_binary, collap_output_df_logical)
#> [1] TRUE  # as expected!
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### Scenario B -- not as expected
The following procedure is identical to the code above, with one exception. Here, I'm going to use data that has several more rows, and values (`1`s and `0`s) are distributed somewhat differently. But that **should not affect in any way** on how `collap()` operates.

``` r
library(collapse)
#> collapse 1.6.5, see ?`collapse-package` or ?`collapse-documentation`
#> Note: stats::D  ->  D.expression, D.call, D.name
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D

df_binary_2 <- 
  data.frame(col_animal = rep(c("cat", "dog"), each = 5),
             col_a = c(0, 0, 1, 1, 0, 1, 0, 1, 1, 1),
             col_b = c(1, 1, 1, 0, 0, 0, 0, 0, 0, 0))

collap_output_df_binary_2 <- collapse::collap(df_binary_2, by = ~col_animal, FUN = any)
#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

#> Warning in FUN(X[[i]], ...): coercing argument of type 'double' to logical

# to avoid the warning, let's repeat the collap() procedure, but convert data as logical first
df_logical_2 <- df_binary_2
df_logical_2$col_a <- as.logical(df_logical_2$col_a)
df_logical_2$col_b <- as.logical(df_logical_2$col_b)

collap_output_df_logical_2 <- collapse::collap(df_logical_2, by = ~col_animal, FUN = any)

identical(collap_output_df_binary_2, collap_output_df_logical_2)
#> [1] FALSE # unexpected!
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<h4>Taking a closer look</h4>

We started with `df_binary_2`:

```r
df_binary_2
#>    col_animal col_a col_b
#> 1         cat     0     1
#> 2         cat     0     1
#> 3         cat     1     1
#> 4         cat     1     0
#> 5         cat     0     0
#> 6         dog     1     0
#> 7         dog     0     0
#> 8         dog     1     0
#> 9         dog     1     0
#> 10        dog     1     0
```
Then ran `collap_output_df_binary_2 <- collapse::collap(df_binary_2, by = ~col_animal, FUN = any)` such that:

```r
collap_output_df_binary_2
#>   col_animal col_a col_b
#> 1        cat  TRUE  TRUE
#> 2        dog  TRUE FALSE
```
So far everything is correct. But then we sought to first convert `col_a` and `col_b` to `logical` _before_ running `collap()`.

```r
df_logical_2
#>    col_animal col_a col_b
#> 1         cat FALSE  TRUE
#> 2         cat FALSE  TRUE
#> 3         cat  TRUE  TRUE
#> 4         cat  TRUE FALSE
#> 5         cat FALSE FALSE
#> 6         dog  TRUE FALSE
#> 7         dog FALSE FALSE
#> 8         dog  TRUE FALSE
#> 9         dog  TRUE FALSE
#> 10        dog  TRUE FALSE
```

But here comes trouble:

```r
collap_output_df_logical_2 <- collapse::collap(df_logical_2, by = ~col_animal, FUN = any)
collap_output_df_logical_2
#>   col_animal col_a col_b
#> 1        cat FALSE  TRUE
#> 2        dog  TRUE FALSE
```
How come that `cat` in `col_a` got `FALSE` when collapsed with `any()`?

---
Unless I have a mistake in my own code, this seems like a bug. I've run into this issue over larger datasets, and I cannot detect the pattern for the error. Here I captured it with scenario A vs scenario B.

**Comment by SebKrantz** [comment]
Thanks, I'll try to look into this during the weekend.

**Comment by SebKrantz** [comment]
I finally figgures this out, sorry for the delay. This is not an issue at all, but you need to be aware what you are doing. `collap` is a very flexible command designed for mixed-type data, you have arguments `FUN` and `catFUN`, where `FUN` are functions applied to numeric data and `catFUN` are functions applied to non-numeric data. The default is `FUN = fmean` and `catFUN = fmode`. Thus a numeric vector of zeros and ones is handled by `FUN`, but a logical vector is handled by `catFUN`.  So the reason you get a wrong result in 

```
collapse::collap(df_logical_2, by = ~col_animal, FUN = any)
```
is because your now categorical data is actually being aggregated with `fmode`, not with `any`. The correct specification would be
```
collapse::collap(df_logical_2, by = ~col_animal, catFUN = any)
```
which also gives the right result. I understand that this is somewhat unintuitive and it also took me a while to figure it out. I don't think there is anything I can do about it though. `collap` was designed with complex tasks in mind, and for those tasks it has sensible defaults.
