### ISSUE TITLE
`collapse::fmode()` has `ties` argument; is there a reason why there's no `"last"` method?

### ISSUE THREAD

**Issue by emmansh** [SebKrantz/collapse#195]
I went over [`fmode()` documentation page](https://sebkrantz.github.io/collapse/reference/fmode.html) but didn't find discussion about why there's `"first"` method but not `"last"`.

**Comment by emmansh** [comment]
[This StackOveflow comment](https://stackoverflow.com/questions/69928678/finding-the-statistical-mode-of-a-vector-when-having-more-than-single-mode-re#comment123613577_69928678) advises to use:
```r
fmode(rev(x), ties = "first")
```
Which is great when applied on standalone vector objects but not with data grouped using `{collapse}` functions. The values in the output get jumbled up. I assume this is because of a conflict between `collapse::fmode()` and `base::rev()`: whereas `fmode()` "understands" data grouped with `collapse` methods, `rev()` does not.

**Comment by SebKrantz** [comment]
Thanks, I have answered on GitHub, and I will try to add the `"last"` option, if I manage to do that in a way that doesn't comproise the speed of the algorithm.
