### ISSUE TITLE
Feature request: print feedback

### ISSUE THREAD

**Issue by statzhero** [SebKrantz/collapse#196]
I'm sure this is no small ask but if you are looking for further features, may I suggest a feedback system for typical data manipulation. A great example for `dplyr` is the [tidylog package](https://github.com/elbersb/tidylog).

**Comment by SebKrantz** [comment]
Thanks! I'm working on a major release which will be out by the end of this week. I like the idea of feedback and if I do joins (maybe for the next release), I will have them give feedback by default. For the rest of the functions, I don't think feedback will be implemented soon, but I'll keep it in mind.

**Comment by statzhero** [comment]
Cool – merging data is definitely the most critical use case.

**Comment by SebKrantz** [comment]
*collapse* provides verbosity for critical operations such as joins (and, optionally, for pivots using the `check.dups` argument to `pivot`). It also prints informative statistics below grouped/indexed data frames. I don't think further levels of verbosity will be implemented in the near future. So I will close this issue.
