### ISSUE TITLE
Contribute to base R

### ISSUE THREAD

**Issue by t-wojciech** [SebKrantz/collapse#198]
Great package! Have you thought about improving some functions directly in R? Then more users could benefit from your work.

**Comment by SebKrantz** [comment]
Thanks! I agree that I’d love to see some things (such as math by reference) implemented in base R. However it is very difficult to contribute to base R, and typically R Core does not have time to consider such contributions. Usually it happens after a certain package or feature becomes very popular, an then still they typically still do their own (as you can see regarding the new base pipe).

**Comment by t-wojciech** [comment]
I think it's still worth a try, if you have time. Of course, not all functions at once, at the beginning it would be best to rewrite the simplest ones (e.g. scale?). Recently I saw CRAN created a new [R Contributor Site](https://contributor.r-project.org/) website so maybe now they will be more interested? Thanks anyway!

**Comment by SebKrantz** [comment]
Thanks! Let me first finalize this release and see more responses to it and then I'll consider this.

**Comment by SebKrantz** [comment]
I have put a [post](https://stat.ethz.ch/pipermail/r-devel/2022-February/081507.html) in this regard onto the R-devel mailing list, but nobody has responded yet, and I don't think this will be fruitful. Contributing to base R remains very difficult and I think it's better to focus on package development.

**Comment by t-wojciech** [comment]
It's a pity there's no interest from the R developers, but thanks for trying. However, it's good that your package exists.

**Comment by kadyb** [comment]
@SebKrantz BTW: This week is the start of R Project Sprint 2023 and we can see that some of the issues are related to R optimization on the low-level side (check: https://github.com/r-devel/r-project-sprint-2023/issues). Now it's probably too late and you don't have time, but it seems to be an opportunity (or in the future) to implement the fixes you suggested.

**Comment by SebKrantz** [comment]
Thanks. I’ve had a glance, but I don’t think they are interested in
ambitious low-level optimizations of fundamental algorithms (like hashing
etc.). Given the non-response/interest of R core in my proposals, I think
I’m out of that game. But I’m working on collapse 2.0 which will provide
further improvements in fundamental operations like matching and joining.
