### ISSUE TITLE
Feature request: eliminate quoted references to column names in functions

### ISSUE THREAD

**Issue by tedmoorman** [SebKrantz/collapse#218]
_collapse_ is a very powerful package. I'm very impressed! Because of it, I see value in transitioning away from the equivalent _dplyr_ way of doing things.

I've had some difficulty using the package functions to define my own functions. [For example, see my post here.](https://stackoverflow.com/questions/70963235/refer-to-quoted-column-name-in-a-function-in-r)

While some packages contain functions requiring quoted references to data frame columns, 
for example, `collapse::na_omit(cols = c(glue("{col}")))`, others have moved away from this (notably, _dplyr_ and other _tidyverse_ packages). I'm just wondering if it might be a goal of the package to eliminate these quoted references to columns. If not, then perhaps you can suggest a workaround for this in my own functional programming.

Thanks for considering!

**Comment by SebKrantz** [comment]
Hi, thanks for the compliment. I've answered on stackoverflow. I don't think anything needs to be added to the package?

**Comment by tedmoorman** [comment]
Thank you for providing a great solution. The `as.character(substitute())` was exactly what I was looking for.
