### ISSUE TITLE
Error related to ftransform

### ISSUE THREAD

**Issue by tedmoorman** [SebKrantz/collapse#222]
I can run all of the following code without errors:
```
my_df <-
  data.frame(
    matrix(
      c(
        "V9G","Blue",
        NA,"Red",
        "J4C","White",
        NA,"Brown",
        "F7B","Orange",
        "G3V","Green"
      ),
      nrow = 6,
      ncol = 2,
      byrow = TRUE,
      dimnames = list(NULL,
                      c("color_code", "color"))
    ),
    stringsAsFactors = FALSE
  )

library(collapse)
library(dplyr)
library(stringr)

func1 <- function(df, col){
  env <- list2env(df, parent = parent.frame())
  col <- substitute(col)
  df %>%  
    collapse::ftransform(count = stringr::str_length(eval(col, env)))
}

func1(my_df, color_code)

func2 <- function(df, col) {
  col_char_ref <- deparse(substitute(col)) #Use deparse(substitute()) to refer to a quoted column name
  df %>% 
    collapse::na_omit(cols = col_char_ref) 
}

func2(my_df, color_code)
```
Then when I attempt to combine the two functions as follows:
```
func3 <- function(df, col){
  env <- list2env(df, parent = parent.frame())
  col <- substitute(col)
  df %>%  
    collapse::na_omit(cols = deparse(col)) %>% 
    collapse::ftransform(description = stringr::str_length(eval(col, env)))
}

func3(my_df, color_code)
```
I get the following error message:
```
Error in ftransform_core(.data, e) : 
  Lengths of replacements must be equal to nrow(.data) or 1, or NULL to delete columns
```
Any idea what's going on?

**Comment by SebKrantz** [comment]
So first of all I fundamentally don't understand why you need to use `ftransform`, `list2env` and pipes inside this function. Something like this would be sufficient:

```
func3 <- function(df, col) {
  col <- as.character(substitute(col)) # as.character (single column) or all.vars (multiple columns) are faster than deparse and work equally well
  df <- na_omit(df, cols = col) 
  df$count <- stringr::str_length(.subset2(df, col))
  df
}

# Other options that are less efficient:

func3 <- function(df, col) {
  col <- substitute(col)
  df <- na_omit(df, cols = as.character(col)) 
  df$count <- stringr::str_length(eval(col, df, parent.frame()))
  df
}

func3 <- function(df, col) {
  col <- substitute(col)
  df <- na_omit(df, cols = as.character(col)) 
  ftransform(df) <- list(count = stringr::str_length(eval(col, df, parent.frame())))
  df
}
```
In general, I wonder why you don't just use standard evaluation e.g.
```
func3 <- function(df, col) {
  df <- na_omit(df, cols = col) 
  df$count <- stringr::str_length(.subset2(df, col))
  df
}
```

**Comment by tedmoorman** [comment]
I must be using the _dplyr_ way of programming with pipes and lots functional verbs like mutate, select, etc. I guess I've been doing non-standard evaluation programming (if that's what it is) for a while now. It looks like it's something I need to unlearn if I want to do more efficient programming and to use the _collapse_ package.

**Comment by SebKrantz** [comment]
Yeah, NSE programming is not a good idea in base R or collapse, which is build on base R and C/C++. You should seek to either turn your expressions into standard things at the beginning of the functions, or avoid NSE function inputs alltogether.

**Comment by tedmoorman** [comment]
> .. and pass your column as a character string.
So many functions seem to have gotten away from requiring columns to be passed as character strings. I'd rather not have users trying to figure out whether columns need to be quoted or not when submitted as parameters.  Maybe this expecting too little of users or making them lazy when it comes to reading documentation?

**Comment by SebKrantz** [comment]
So in principal, you have 3 options:

 (1) you do your own NSE using `as.character(substitute())` and then use standard evaluation collapse functions (see my examples above). 

(2) You pass down arguments directly to NSE functions using `...` e.g. `fun <- function(x, ...) fselect(x, ...)` or `fun <- function(x, ...) ftransform(x, ...)`. As I showed you `fselect`has a `return`argument that can help you turn your column expressions into various things. Another option you have is the `.c`function in the package which simply returns the character vector directly e.g. `fun <- function(x, ...) vars <- .c(...)` just gives the arguments `...`as a character string `vars`. 

(3) You can also put the whole function call into `substitute()` and then evaluate with `eval()` e.g. 

``` r
library(collapse)
fun <- function(x, y) {
  x <- x # This makes sure "x" is available inside the function environment where we evaluate the ftransform expression
  eval(substitute(ftransform(x, new = y)))
}
# This creates a column "new" using ftransform
fun(mtcars, mpg + hp / mean(carb)) |> head()
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb      new
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4 60.11111
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4 60.11111
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1 55.86667
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1 60.51111
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2 80.92222
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1 55.43333
```

<sup>Created on 2022-02-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
