### ISSUE TITLE
Adding r-collapse to conda-forge

### ISSUE THREAD

**Issue by hermidalc** [SebKrantz/collapse#227]
Would be great if `collapse` could be made available for mambaforge/miniforge on the `conda-forge` channel. Many use mamba/conda to do soft dev and create reproducible environments and workflows that others can easily install and I would like to use `collapse`

**Comment by SebKrantz** [comment]
Thanks, I'm not very familiar with conda, I presume you mean [this](https://conda-forge.org/docs/maintainer/adding_pkgs.html). I can look into this during the weekend, but if you know how to do this e.g. by forking collapse and sending a PR, that would be of great help.

**Comment by hermidalc** [comment]
https://conda-forge.org/#contribute

Unfortunately I’m not super familiar with creating new conda-forge recipes and feedstocks.

I just use conda, conda-forge, bioconda, and mambaforge ecosystem a lot to write code. Conda is really huge for Python and R users so would give your library a lot more visibility and user base by being part of the conda-forge ecosystem.
  
I’m guessing that under the `conda-forge` GitHub organization you would basically create a feedstock repository called `r-collapse-feedstock` for the `r-collapse` package with your recipe and build details like for example the one for `dplyr` https://github.com/conda-forge/r-dplyr-feedstock. Most every R library can be found in conda-forge, maybe worth looking at other feedstock repos to get more info on how to set things up.

**Comment by SebKrantz** [comment]
Thanks, I have submitted a recipe now, you can follow the progress [here](https://github.com/conda-forge/staged-recipes/pull/18018).

**Comment by trang1618** [comment]
Amazing! I was just going to ask for this and see that the issue has been open! Excited to see r-collapse on conda-forge!

**Comment by SebKrantz** [comment]
Thanks, yeah we're waiting. If anything should be done to speed up the process let me know.

**Comment by SebKrantz** [comment]
The PR has been accepted.

**Comment by hermidalc** [comment]
Will test it soon!
