### ISSUE TITLE
Feature request: Fast substitute for plm::pvar

### ISSUE THREAD

**Issue by helix123** [SebKrantz/collapse#24]
The function `pvar` in `plm` is notoriously slow. A fast function for the same purpose is `are_varying` in package `panelr` but it requires package `dplyr` as a dependency.

Do you plan a drop-in replacement for `pvar` (without additional dependencies, i.e., just `Rcpp`)?

BTW: This is a very interesting package! I am thinking since a while if `plm` could have an option to make use of the faster versions of transformations supplied by this package as they seem to be drop-in replacements  (if the package is available on the users local machine). The additional dependency burden with `collapse` and - in turn - `Rcpp` seems quite low.

**Comment by SebKrantz** [comment]
Hi helix123, thanks for your request, yes this is easy to program in C++, I am happy to add it in the next release (which will hopefully be already by the end of this week). When I look at panel data I usually prefer to panel-summarize it with qsu and look at the between and within standard deviation, which gives me information not only about which variables vary over which dimension, but in what magnitude. But In understand pdim is a nice shortcut for data.frames with many variables. So it will be there in C++ in the next release (no extra dependencies). I also note that you can already programm something like an efficient pdim with existing functionality. For multitype panel data:

```
fvarying_over <- function(data, dimvar) {
  dimi <- attr(data, "names") %!in% dimvar
  r <- get_vars(collapv(wlddev, dimvar, fsd, fNdistinct), dimi)
  group_na <- dapply(r, anyNA)
  r <- fmean(r)
  num <- num_vars(get_vars(data, dimi), "indices")
  r[num] <- r[num] + 1
  cat("Varying over", dimvar, ": ", names(which(r > 1)), "\n") 
  cat("Not varying over", dimvar, ": ", names(which(r <= 1)), "\n") 
  cat("all NA in dimension", dimvar, "for at least one entity: ", names(which(group_na)), "\n") 
}

# Example:
fvarying_over(wlddev, "country")
```

This is about 150x faster than pdim, and 100x faster than are_varying, but it of course involves aggregating numeric variables with the standard deviation and categorical variables with the number of distinct values. The C++ implementation will be much simpler and around 1000x faster than pdim.

Regarding integrating collapse into plm, I think it would be great and could speed up plm about 50x. I have honestly not had the time yet to promote this package, very few people know about it, I will take more time after the next release. But if you want to take inititive, feel very free to e-mail the plm authors and copy me in. If they want to do this, I am happy to cooperate with them.
