### ISSUE TITLE
recode_char()

### ISSUE THREAD

**Issue by wevsena** [SebKrantz/collapse#242]
Hi, I can't understand the function behavior in this case:

v <- c("João Pessoa", "Cabedelo", "São Paulo")

recode_char(v, `São Paulo` = "SP", Cabedelo = "CBL")

Best regards!

**Comment by SebKrantz** [comment]
Hi, you can only enter character strings consisting of a single word without quotes. This works for me

```
v <- c("João Pessoa", "Cabedelo", "São Paulo")

recode_char(v, "São Paulo" = "SP", Cabedelo = "CBL")
```
