### ISSUE TITLE
analogous function to dplyr::row_number ?

### ISSUE THREAD

**Issue by tenFnAN** [SebKrantz/collapse#247]
hi, there is an analog function to dplyr::row_number ?, I need to do the following operation a little faster with collapse:
```
  dplyr::group_by(cols_grouping) %>%
  dplyr::mutate(
    day_enum  = dplyr::row_number() 
  ) %>%
  dplyr::ungroup()
```

**Comment by SebKrantz** [comment]
Hi, so there is `data.table::rowid` that does just that e.g. 

```
wlddev %>% fmutate(iso3_num = data.table::rowid(region, income))

```

If you want only collapse, you can use fcumsum on a vector of ones.

```
wlddev %>% fmutate(iso3_num = 1L, iso3_num = fcumsum(iso3_num, list(region, income)))
```
