### ISSUE TITLE
Feature request: lag/lead fill gaps?

### ISSUE THREAD

**Issue by MatthieuStigler** [SebKrantz/collapse#26]
Hi

it would be great if `flag`/`L` and `F` could allow gaps in the timevar? Maybe add an argument `fill_gaps=FALSE` (for backward compatibility), and when `TRUE` add `fill` value for the gaps, instead of stopping?

``` r
library(collapse)
#> collapse 1.1.0, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
data(wlddev)

head(L(wlddev, 1, ~iso3c, ~year, cols="LIFEEX"))
#>   iso3c year L1.LIFEEX
#> 1   AFG 1960        NA
#> 2   AFG 1961    32.292
#> 3   AFG 1962    32.742
#> 4   AFG 1963    33.185
#> 5   AFG 1964    33.624
#> 6   AFG 1965    34.060

## would be nice if this works too:
head(L(wlddev[-3,], 1, ~iso3c, ~year, cols="LIFEEX"))
#> Error in L.data.frame(wlddev[-3, ], 1, ~iso3c, ~year, cols = "LIFEEX"): Gaps in timevar within one or more groups

## Should give: 
dat_complete <- tidyr::complete(wlddev[-3, c("iso3c", "year", "LIFEEX")], iso3c, year= 1960:2018)
head(subset(L(dat_complete, 1, ~iso3c, ~year, cols="LIFEEX"), iso3c=="AFG"))
#> # A tibble: 6 x 3
#>   iso3c  year L1.LIFEEX
#>   <fct> <int>     <dbl>
#> 1 AFG    1960      NA  
#> 2 AFG    1961      32.3
#> 3 AFG    1962      32.7
#> 4 AFG    1963      NA  
#> 5 AFG    1964      33.6
#> 6 AFG    1965      34.1
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Thanks, this is an interesting issue, I've never encountered it. However implementing what you requested seems to me to require a fundamental re-engineering of some of the C++ code to flexibly generate output data.frame's that are potentially longer than the input data.frame. This again throws up other issues with row-names and attributes for special structures like grouped tibbles or pdata.frame's. So This is not something to be implemented soon I think. I'll keep it open for now and think about it, but it is not easy to do this efficiently and securely.

**Comment by MatthieuStigler** [comment]
Lucky you who never had irregular time series or unbalanced panels ;-) By the way, I wasn't sure to understand what you mean in the documentation about *flag / L /F works fine on balanced and unbalanced panel data.*? It seems unbalanced will likely to cause the gap problem, unless by chance the missing observations are the first or last time series, or did i miss something?

Sorry, my example was misleading. Adding the supplementary rows is unnecessary, and does not serve the main point, which is having NA for missing lags. See updated example. So the output would be same as input indeed. 

The main problem is that the `complete()` + `semi_join` approach is to my knowledge the only solution available for now for irregular time series. And this approach is very inefficient and slow. So if there's any chance to have `flag` handle this, that would bring a tremendous speed improvement :-)

Thanks!

``` r
library(collapse)
#> collapse 1.1.0, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
library(tidyverse)

data(wlddev)

head(L(wlddev, 1, ~iso3c, ~year, cols="LIFEEX"))
#>   iso3c year L1.LIFEEX
#> 1   AFG 1960        NA
#> 2   AFG 1961    32.292
#> 3   AFG 1962    32.742
#> 4   AFG 1963    33.185
#> 5   AFG 1964    33.624
#> 6   AFG 1965    34.060
## would be nice if this works too:
head(L(wlddev[-3,], 1, ~iso3c, ~year, cols="LIFEEX"))
#> Error in L.data.frame(wlddev[-3, ], 1, ~iso3c, ~year, cols = "LIFEEX"): Gaps in timevar within one or more groups

## Should give: 
dat_complete <- tidyr::complete(wlddev[-3, c("iso3c", "year", "LIFEEX")], iso3c, year= 1960:2018)
head(subset(L(dat_complete, 1, ~iso3c, ~year, cols="LIFEEX"), iso3c=="AFG") %>% 
       semi_join(wlddev[-3, c("iso3c", "year", "LIFEEX")], by = c("iso3c", "year")))
#> # A tibble: 6 x 3
#>   iso3c  year L1.LIFEEX
#>   <fct> <int>     <dbl>
#> 1 AFG    1960      NA  
#> 2 AFG    1961      32.3
#> 3 AFG    1963      NA  
#> 4 AFG    1964      33.6
#> 5 AFG    1965      34.1
#> 6 AFG    1966      34.5
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
So I understand an unbalanced panel to be a panel with an unequal time-coverage for each individual. The `GGDC10S` dataset included in collapse is such a panel and you can lagg it `L(GGDC10S,1,~Variable+Country, ~Year)`. collapse also supports unbalanced panels with irregular gaps such as a panel survey with repreated observations conducted every two years -> the irregular gaps become regular ones through conversion to factor. The only thing it cannot curently do is lag panels where some individual is arbitrarily missing a time period somewhere in the middle, which to me seems to be a very strange thing: If it occurs rarely for one or two people, why don't make a proper panel by inserting a row? If you are randomly observing different periods for different people, how are you going to analyze that and why would you want to lag that (producing lots of NA's)? 

The reason This is currently not supported is simple: What the C++ does is create an ordering vector of the panel i.e. `o <- order(pid, t)` and then runs through the data replacing `x` with `x[o[-n]]` while replacing the first `n` periods in each group with NA. To implement What you are requesting woudl require creating a second vector keeping track of the gaps to fill those with NA, with associated extra memory cost. If I do this I would do it only with an extra argument i.e. `irregular = TRUE` or something. But before I develop something like that I would like to understand where this legitimately arises?

**Comment by SebKrantz** [comment]
So I have thought about this a bit now. I don't think I can make a straightforward change to have this code handle irregular spaced time-series. That would require some re-engineering (If you have any ideas feel free to look at src/flag.cpp lines 125+). What I can do for you is the following: It seems to me that any irregular spaced time-series or panel can be expressed as a regular spaced one with a different panel-id (I presume that is what STATA does when you tsset data). So all you need to do is create an appropriate panel-id that treats all observations after the gap in your individual as a new individual. This could be difficult to do in R, so what I can do is create a C++ function `gapid` that runs through the time-variable in a sorted panel-data set and creates a new id whenever observations are not consecutive. With this new id, you can then use `flag` and other functionality on the panel.

**Comment by MatthieuStigler** [comment]
Dear Sebastian

Sorry for late reply, had an urgent deadline. To describe the specific application I have in mind, I am working with a large dataset of fields, where we observe crop choice over many years with satellite data. Issue is that clouds in a particular year might give rise to NA. I take your point that taking multiple lags brings many NAs, and hence one wonders why one would want to keep observations at all. Indeed, I discard those unit-years observations for which there are NAs/missing years. Yet I still keep those years for the same unit that have full lags. 

This is currently difficult to do in R in a time-effective way. The only way pretty much is the "row addition" you describe, conveniently made using `tidyr::complete`. but potentially very costly. The idea of using the `gapid` approach as you suggest is interesting, although it implies one could not get lag 3 is lag 2 is missing (something the complete appraoch would allow). But I reckon that the approach filling missing with NAs would be complicated, as it would require computing lags of the time variable itself, have a benchmark time-lag interval (easy for year, harder for dates), and then ordering/filling those values for which time lag is different. So quite complicated indeed.

So at this point, I suggest we can close this issue, but if you want to keep this in mind if once you get inspired, that could be a valuable :-)

Thanks a lot!!

**Comment by SebKrantz** [comment]
Hi Matthieu,

Ok it's cool. I already created the function though and will include it in the next update. I am not sure I fully understand your second paragraph, in particular the use of `tidyr::complete` in addition to what `seqid` (the final name of the function) could offer. If you don't mind perhaps just give it a shot and let me know which problems you can or cannot solve with this approach. I am attaching the source code: 

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
IntegerVector seqid(const IntegerVector& x, const SEXP& o = R_NilValue, int del = 1, int start = 1,
                    bool na_skip = false, bool skip_seq = false, bool check_o = true) {
  int l = x.size(), prev, id = start;
  IntegerVector out = no_init_vector(l);
  if(Rf_isNull(o)) {
    if(na_skip) {
      int j = 0, end = l-1;
      while(x[j] == NA_INTEGER && j != end) out[j++] = NA_INTEGER;
      if(j != end) {
        prev = x[j];
        out[j] = id;
        for(int i = j+1; i != l; ++i) {
          if(x[i] != NA_INTEGER) {
            if(x[i]-prev != del) ++id; // x[i]-x[i-1]??
            prev = x[i];
            out[i] = id;
          } else { // Faster way ??
            out[i] = NA_INTEGER;
            if(skip_seq) prev += del;
          }
        }
      }
    } else {
      prev = x[0];
      out[0] = id;
      for(int i = 1; i != l; ++i) {
        if(x[i]-prev != del) ++id; // x[i]-x[i-1]??
        prev = x[i];
        out[i] = id;
      }
    }
  } else {
    IntegerVector oo = o;
    int val(oo[0]-1);
    if(val < 0 || val >= l) stop("o out of allowed range [1, length(x)]");
    if(na_skip) {
      int j = 0, end = l-1;
      if(check_o) {
        while(x[val] == NA_INTEGER && j != end) {
          out[val] = NA_INTEGER;
          val = oo[++j]-1;
          if(val < 0 || val >= l) stop("o out of allowed range [1, length(x)]");
        }
        if(j != end) {
          prev = x[val];
          out[val] = id;
          for(int i = j+1; i != l; ++i) {
            val = oo[i]-1;
            if(val < 0 || val >= l) stop("o out of allowed range [1, length(x)]");
            if(x[val] != NA_INTEGER) {
              if(x[val]-prev != del) ++id; // x[i]-x[i-1]??
              prev = x[val];
              out[val] = id;
            } else {
              out[val] = NA_INTEGER;
              if(skip_seq) prev += del;
            }
          }
        }
      } else {
        while(x[val] == NA_INTEGER && j != end) {
          out[val] = NA_INTEGER;
          val = oo[++j]-1;
        }
        if(j != end) {
          prev = x[val];
          out[val] = id;
          for(int i = j+1; i != l; ++i) {
            val = oo[i]-1;
            if(x[val] != NA_INTEGER) {
              if(x[val]-prev != del) ++id; // x[i]-x[i-1]??
              prev = x[val];
              out[val] = id;
            } else {
              out[val] = NA_INTEGER;
              if(skip_seq) prev += del;
            }
          }
        }
      }
    } else {
      prev = x[val];
      out[val] = id; // faster than iterator ??
      if(check_o) {
        for(int i = 1; i != l; ++i) { //   for(IntegerVector::iterator it = oo.begin()+1, end = oo.end(); it != end; ++it) { val = *it-1;
          val = oo[i]-1;
          if(val < 0 || val >= l) stop("o out of allowed range [1, length(x)]");
          if(x[val]-prev != del) ++id;
          prev = x[val];
          out[val] = id;
        }
      } else {
        for(int i = 1; i != l; ++i) { //   for(IntegerVector::iterator it = oo.begin()+1, end = oo.end(); it != end; ++it) { val = *it-1;
          val = oo[i]-1;
          if(x[val]-prev != del) ++id;
          prev = x[val];
          out[val] = id;
        }
      }
    }
  }
  out.attr("N.groups") = id - start + 1;
  out.attr("class") = na_skip ? "qG" : CharacterVector::create("qG", "na.included");
  return out;
}
```
To test, save as 'seqid.cpp' and then compile using `Rcpp::sourceCpp("seqid.cpp")`. The arguments are: `x` the integer time-variable (or factor), `o` an optional ordering vector if the panel is unordered, `del` the time increment between two consecutive observations, `start` the value of the first id, `na_skip = TRUE` will skip missing values such that a sequence `c(1, NA, 2)` becomes `c(1, NA, 1)` (default behavior is `c(1, 2, 3)` so that each `NA` would be interpreted as the start of a new sequence) and if also `skip_seq = TRUE`, then a sequence `c(1, NA, 3)` becomes `c(1, NA, 1)`  (i.e. missing values are seen as part of the sequence. `check_o` is just a programmers option to avoid checking the ordering vector for increased speed.

Best regards,

Sebastian

**Comment by MatthieuStigler** [comment]
Thanks Sebastian! 

What I meant is what with the _subgroup_ approach (as opposed to the _complete_ one), if I miss year 1962, then lag(1963, 1) will be indeed NA, but lag(1963, 2) will be also NA. However, with a _complete_ approach, lag(1963, 2) will be filled with the existing value from 1961. See code below to illustrate the issue:

Thanks!!

``` r
library(collapse)
#> collapse 1.1.0, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
library(tidyverse)
Rcpp::sourceCpp("~/temp/collapse/seqid.cpp")

data(wlddev)
data <- as_tibble(wlddev[, c("iso3c", "year", "LIFEEX")]) %>% 
  arrange(iso3c, year) %>% 
  slice(-3)



## strategy one: complete
dat_complete <- tidyr::complete(data, iso3c, year= 1960L:2018L)
#> Warning: Column `year` has different attributes on LHS and RHS of join
L(dat_complete, 1:3, ~iso3c, ~year, cols="LIFEEX") %>% 
  semi_join(data, by  =c("iso3c", "year"))
#> Warning: Column `year` has different attributes on LHS and RHS of join
#> # A tibble: 12,743 x 5
#>    iso3c  year L1.LIFEEX L2.LIFEEX L3.LIFEEX
#>    <fct> <int>     <dbl>     <dbl>     <dbl>
#>  1 ABW    1960      NA        NA        NA  
#>  2 ABW    1961      65.7      NA        NA  
#>  3 ABW    1963      NA        66.1      65.7
#>  4 ABW    1964      66.8      NA        66.1
#>  5 ABW    1965      67.1      66.8      NA  
#>  6 ABW    1966      67.4      67.1      66.8
#>  7 ABW    1967      67.8      67.4      67.1
#>  8 ABW    1968      68.1      67.8      67.4
#>  9 ABW    1969      68.4      68.1      67.8
#> 10 ABW    1970      68.8      68.4      68.1
#> # … with 12,733 more rows

## strategy 2: subgroups
data %>% 
  mutate(seqid = seqid(x=data$year, del=1)) %>% 
  L(1:3, ~seqid, ~year, cols="LIFEEX")
#> # A tibble: 12,743 x 5
#>    seqid  year L1.LIFEEX L2.LIFEEX L3.LIFEEX
#>  * <qG>  <int>     <dbl>     <dbl>     <dbl>
#>  1 1      1960      NA        NA        NA  
#>  2 1      1961      65.7      NA        NA  
#>  3 2      1963      NA        NA        NA  
#>  4 2      1964      66.8      NA        NA  
#>  5 2      1965      67.1      66.8      NA  
#>  6 2      1966      67.4      67.1      66.8
#>  7 2      1967      67.8      67.4      67.1
#>  8 2      1968      68.1      67.8      67.4
#>  9 2      1969      68.4      68.1      67.8
#> 10 2      1970      68.8      68.4      68.1
#> # … with 12,733 more rows
```

<sup>Created on 2020-05-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Thanks Matthieu, I now understand it, although I still do not fully grasp the analytical value of doing this (if you run a regression both should give the same if only complete cases are used, unless of course you don't use a sequence of lags but just, say, lag 2). As it stands, on the spot I don't know how to implement this. Maybe I will have some ideas in the future. This hour I am updating collapse. v1.2.0 is a major release (github is already available). It includes things like `seqid`, but also a function `radixorder` for fast ordered grouping (i.e. it returns both an ordering vector and also a grouping information). Perhaps with the set of tools provided by `seqid`, `groupid`, `radixorder` and `data.table::rowid`, and `data.table::nafill`, you are able to devise an effective solution to the problem in R. Let me know if you do, and thanks again for helping make this package better!

**Comment by SebKrantz** [comment]
Hi Matthieu, this is to let you know that I have been able to modify my lagging algorithm to natively perform a complete approach to lagging and differences / growth rates for irregular time series and panels - without noticeable decline in performance. The only thing that is not really working yet is iterated differences on irregular time series and panels - the algorithm to efficiently perform iterated differences is already quite complex, and I did not manage to (out of the box) include the irregularity there. If you have time feel free to test with some of your datasets and give me feedback. You can install collapse 1.5 from Github. Happy holidays.
