### ISSUE TITLE
Support for `flm.formula` method

### ISSUE THREAD

**Issue by grantmcdermott** [SebKrantz/collapse#291]
Hi Sebastian,

Personally, I really like the `flm` function. But the low(er) level requirement of passing two matrix arguments does make it trickier for more novice users. 

Would you consider adding support for a `flm.formula` convenience method, whereby users could pass regular formula + data frame arguments and it would do the necessary model.matrix conversion internally (or pass to `qM` and co.)? So something like `flm(mpg ~ wt, mtcars)` would Just Work$^{TM}$.

In essence, I'm thinking of something similar to the dispatch logic that, say, `graphics:::plot.formula` uses, but with **collapse** power behind it.

As ever, thanks for for considering.

**Comment by SebKrantz** [comment]
Thanks Grant, I will not make `flm` S3 generic as that costs too much in terms of performance for such a function, however I can add a function (using fixest's naming suggestion): 

```
flm_fml <- function(formula, data, weights = NULL, add.icpt = TRUE, ...) {
  tms <- attributes(terms.formula(formula))
  pe <- tms[[".Environment"]]
  mf <- eval(tms$variables, data, pe)
  y <- mf[[1L]]
  X <- mf[-1L]
  w <- eval(substitute(weights), data, pe)
  names(X) <- tms$term.labels
  if(add.icpt) X <- c(list(`(Intercept)` = alloc(1, length(y))), X)
  flm(y, do.call(cbind, X), w, FALSE, ...)
}
```
This one will allow transformations of variables e.g. `flm_fml(log(mpg) ~cyl + log(hp), mtcars, weights = log(wt))`, but no factors or interactions. 

By the way, just had an intensive exchange with Brodie Gaslam about bivariate grouped regression. For such cases the following will be hard to beat. 
```
library(collapse)
n <- 1e7
x <- runif(n)
y <- runif(n)
g <- cumsum(sample(c(TRUE, rep(FALSE, 9)), n, replace=TRUE))
df <- data.frame(x, y, g)

df |> gby(g) |> mtt(dmx = W(x, na.rm = FALSE)) |> smr(slope = fsum(dmx, y) %/=% fsum(dmx^2))
```

**Comment by SebKrantz** [comment]
Actually I think I will make `flm` generic but without S3 Method dispatch, simply using 
```
flm <- function(...) if(is.atomic(..1)) flm.default(...) else flm.formula(...)

```
the cost is negligible (nanoseconds).

**Comment by grantmcdermott** [comment]
Excellent, thanks @SebKrantz!

Two FWIWs:

1. Yes, I recall Brodie posting an example along those lines on his blog a while back. The cumsum trick is a good one. 
2. Partly, I'm requesting this issue b/c I'm constructing a set of benchmarks for colleagues. For example, I now have access to Stata 17 MP (16 core) at work, so I want horserace a variety of common tasks on big-ish (5 GB) datasets. You'll be please to know that currently **collapse** sets the standard for a bunch of tasks, often by some distance.

**Comment by SebKrantz** [comment]
Ok, that's interesting to know! I've also become aware that STATA has gotten a massive performance upgrade. Regardless of that, my primary reasons for R remain flexibility, development speed and open source. Thanks also again for suggesting this, I now have given `fFtest` a similar treatment with a 2-part formula solution, and I am finding the function much more useful that way: https://sebkrantz.github.io/collapse/reference/fFtest.html
