### ISSUE TITLE
groupid with na.skip: strange result on vector with leading NA

### ISSUE THREAD

**Issue by Henrik-P** [SebKrantz/collapse#335]
First, thanks a lot for an excellent package! 

When using `groupid` with `na.skip = TRUE` on a vector with `NA` only or with leading `NA`, strange values are generated. In addition, the result may differ when the function is called repeatedly on the same vector. Some examples, where `replicate` is used to apply `groupid` to the same vector several times (here: 5):

```
# input: NA; expected result: NA 
replicate(5, groupid(NA, na.skip = TRUE))
# [1]          1 2061486624          1          1 2061582184

# input: c(NA, NA); expected result: c(NA, NA)
replicate(5, groupid(c(NA, NA), na.skip = TRUE))
#       [,1] [,2] [,3] [,4]  [,5]
# [1,]    NA   NA   NA   NA    NA
# [2,] 10082 8380 2754 5814 10529

# input: c(NA, "a"); expected result: c(NA, 1)
replicate(5, groupid(c(NA, "a"), na.skip = TRUE))
#       [,1]        [,2] [,3] [,4] [,5]
# [1,]   NA          NA   NA   NA   NA
# [2,]  480 -1074790400  480  480  480

# input: c(NA, NA, "a"); expected result: c(NA, NA, 1)
replicate(5, groupid(c(NA, NA, "a"), na.skip = TRUE))
#             [,1]       [,2]       [,3] [,4]       [,5]
# [1,]         NA         NA         NA   NA         NA
# [2,]         NA         NA         NA   NA         NA
# [3,] 2037730600 2073769656 2037730600    0 2061479888

# a further demonstration of the range of strange values produced
table(replicate(1000, groupid(NA, na.skip = TRUE)))

```

---------

I (re-)tried in a freshly installed R 4.2.2 session, but the issue remained. Still, I have a nagging feeling that something is corrupt on my side. Would be interesting to see if anyone is able to reproduce.

 
```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] collapse_1.8.9

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2    parallel_4.2.2 Rcpp_1.0.9
```

**Comment by SebKrantz** [comment]
Thanks! No you are correct that there is some sloppyness in the implementation here. The outcome vector is not initialized with any value (empty memory), which can appear as arbitrary values in R. Missing values are skipped in the loop so that memory is not mapped. I will add a check to replace initial values with NA this evening and push it to GitHub.

**Comment by SebKrantz** [comment]
Thanks, it turned out to be a wrong index initialization in C++. The fix is now in the main branch.
