### ISSUE TITLE
`fnrow()` returns error for 0-column data frames

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#344]
Hi, I noticed that `fnrow()` throws an out of bounds error when called on a data frame with 0 columns.
See an example below.

```
> library(collapse)
collapse 1.9.0.9000, see ?`collapse-package` or ?`collapse-documentation`

Attaching package: ‘collapse’

The following object is masked from ‘package:stats’:

    D

data(iris)
iris2 <- iris[, NULL, drop = FALSE]
iris3 <- iris[NULL, , drop = FALSE]
iris4 <- iris[NULL, NULL, drop = FALSE]
nrow(iris2)
[1] 150
ncol(iris2)
[1] 0
nrow(iris3)
[1] 0
ncol(iris3)
[1] 5
nrow(iris4)
[1] 0
ncol(iris4)
[1] 0
fnrow(iris2)
Error in .subset2(X, 1L) : subscript out of bounds
fncol(iris2)
[1] 0
fnrow(iris3)
[1] 0
fncol(iris3)
[1] 5
fnrow(iris4)
Error in .subset2(X, 1L) : subscript out of bounds
fncol(iris4)
[1] 0
```

Many thanks

**Comment by NicChr** [comment]
Thanks, I would add that I think it affects other functions such as `seq_row()` and `fsubset()` for the special case of 0-column data frames.

Would something like this maybe work? 
```r
fnrow <- function (X){
    if (inherits(X, "data.frame")){
        length(attr(X, "row.names", exact = TRUE))
    } else {
        NULL
    }
}
```
You can maybe use the fact that data.frames have a row.names attribute though it's a bit slower than `collapse::fnrow()` but still faster than `nrow()`.

**Comment by SebKrantz** [comment]
Thanks. I have rewritten fnrow in C. It is in the main branch now.
