### ISSUE TITLE
Collapse diverging from base when encoding unknown

### ISSUE THREAD

**Issue by sindribaldur** [SebKrantz/collapse#354]
Came across this when working with data originally imported (but later partly modified) with `readxl` on a Windows 10 machine. Not sure if considered a bug or a feature but I was expecting the same behaviour as base R and other mainstream packages.

I'm using R 4.2.1 and reproduced with both `collapse_1.8.6` and  `collapse_1.8.9`.

```R
> x = c("dæg", "dæg", "dog")
> Encoding(x)
[1] "UTF-8"   "UTF-8"   "unknown"
> Encoding(x[1]) = "unknown"
> Encoding(x)
[1] "unknown" "UTF-8"   "unknown"
> 
> identical(x[1], x[2])
[1] TRUE
> do.call(identical, lapply(x[1:2], charToRaw))
[1] TRUE
> do.call(identical, lapply(x[1:2], utf8ToInt))
[1] TRUE
> 
> unique(x)
[1] "dæg" "dog"
> data.table::uniqueN(x)
[1] 2
> dplyr     ::n_distinct(x)
[1] 2
> collapse  ::fndistinct(x)
[1] 3
> collapse  ::funique(x)
[1] "dæg" "dæg" "dog"
> 
> Encoding(x) = "UTF-8"
> Encoding(x) 
[1] "UTF-8"   "UTF-8"   "unknown"
> collapse::fndistinct(x)
[1] 2
```

**Comment by SebKrantz** [comment]
Thanks, I can look into this, but not right now as I am preparing a major update. In general though *collapse* is a UTF-8 package (as indicated in the DESCRIPTION), and I presume checking the encoding of individual strings would have a non-negligible performance cost.

**Comment by SebKrantz** [comment]
This issue will not be solved. *collapse* is an UTF-8 package and will not check the encoding of individual strings, because this has a high performance cost.
