### ISSUE TITLE
`descr` to support grouped operations

### ISSUE THREAD

**Issue by statzhero** [SebKrantz/collapse#355]
It's possible this request may have come up before: if `collapse::descr()` serves as a wrapper for `qsu`, would it be possible to support the same grouped operations, at least for dataframes (`by` argument)? 

Alternatively, `qsu` could support further statistics such as extended quantiles.

**Comment by SebKrantz** [comment]
Thanks, I am thinking of adding these capabilities to descr() for the current 1.9.0 update, but not to qsu(), as quantile estimation requires selection algorithms which would unduly slow down qsu().

**Comment by statzhero** [comment]
Yes this makes most sense to me as well.
