### ISSUE TITLE
Error - collapg(), named list of functions, with and without weights

### ISSUE THREAD

**Issue by ttrodrigz** [SebKrantz/collapse#358]
I'm running into an unexpected error using `collapg()` when I want to provide a named list of functions to `FUN`. Everything works correctly when weights are _not_ being used, but results in an error when weights are supplied.

Examples 1 and 2 below work just fine...

#### Example 1: no weights, named list of functions
``` r
library(collapse)

mtcars |> 
    fselect(cyl, mpg, disp) |>
    fgroup_by(cyl) |> 
    collapg(
        FUN = list(
            "fun_1" = mean,
            "fun_2" = median
        ),
        return = "long"
    )
#>   Function cyl      mpg     disp
#> 1    fun_1   4 26.66364 105.1364
#> 2    fun_1   6 19.74286 183.3143
#> 3    fun_1   8 15.10000 353.1000
#> 4    fun_2   4 26.00000 108.0000
#> 5    fun_2   6 19.70000 167.6000
#> 6    fun_2   8 15.20000 350.5000
```

#### Example 2: with weights, functions are not named
```r
mtcars |> 
    fselect(wt, cyl, mpg, disp) |>
    fgroup_by(cyl) |> 
    collapg(
        FUN = list(fmean, fmedian),
        w = wt,
        return = "long"
    )
#>   Function cyl     wt      mpg     disp
#> 1    fmean   4 25.143 25.93504 110.3503
#> 2    fmean   6 21.820 19.64578 185.2387
#> 3    fmean   8 55.989 14.80643 362.1255
#> 4  fmedian   4 25.143 24.40000 120.1000
#> 5  fmedian   6 21.820 19.70000 167.6000
#> 6  fmedian   8 55.989 15.20000 351.0000
```

Things break down when attempting to provide a named list of functions _with_ weights...

#### Example 3: with weights, named list of functions
```r
mtcars |> 
    fselect(wt, cyl, mpg, disp) |>
    fgroup_by(cyl) |> 
    collapg(
        FUN = list(
            "fun_1" = fmean,
            "fun_2" = fmedian
        ),
        w = wt,
        return = "long"
    )
#> Error in fmean.default(X[[i]], ...): length(w) must match length(x)
```
Thank you for taking the time to look at this!

**Comment by SebKrantz** [comment]
Thanks, this currently has to do with the way expressions are parsed in `collap()`. I currently only check the names of the list to decide whether the functions are fast statistical functions or not. So passing `list("fun_1" = fmean, "fun_2" = fmedian)` means collap does not know that you are passing fast statistical functions, and you will find the aggregation will run substantially slower than passing `list(fmean, fmedian)` which makes use of the group-level vectorizatio built into these functions. Weights currently only work with fast statistical functions executed ina vectorized way. So the error is that a full length weight vector is passed to fmean() executed on a split dataset. I will try to update the parsing to make it better. For now I recommend to use `fsummarise(across())` which has a better expression parsing (although no reshaping).

**Comment by ttrodrigz** [comment]
Ah, understood thank you for the clarification.

I didn't know that `across()` was usable inside of `fsummarise()`, that's good to know. How would I go about using weighted calculations in that workflow?

If it helps to provide an example, the specific thing I am trying to accomplish is to take the weighted mean, weighted standard deviation and effective sample size ((∑w)2/∑w2) of an arbitrary number of variables by a group.

If I was to use strictly tidyverse syntax, I would do this:
```r
neff <- function(x, w, na.rm = TRUE) {
    
    valid.locations <- !is.na(x)
    w <- w[valid.locations]
    (sum(w, na.rm = na.rm) ^ 2) / sum(w ^ 2, na.rm = na.rm)
    
}

mtcars |> 
    group_by(cyl) |> 
    summarise(
        across(
            .cols = c(mpg, disp, hp),
            .fns = list(
                "mean"  = ~fmean(.x, w = wt),
                "stdev" = ~fsd(.x, w = wt),
                "eff"   = ~neff(.x, w = wt)
            ),
            .names = "{.fn}_{.col}"
        )
    )

# A tibble: 3 x 10
    cyl mean_mpg stdev_~1 eff_mpg mean_~2 stdev~3 eff_d~4 mean_hp stdev~5
  <dbl>    <dbl>    <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
1     4     25.9     4.28   10.4     110.    26.6   10.4     83.4    19.6
2     6     19.6     1.40    6.92    185.    39.6    6.92   122.     22.0
3     8     14.8     2.64   13.5     362.    70.4   13.5    209.     46.9
# ... with 1 more variable: eff_hp <dbl>, and abbreviated variable names
#   1: stdev_mpg, 2: mean_disp, 3: stdev_disp, 4: eff_disp, 5: stdev_hp
# i Use `colnames()` to see all variable names
```

My goal here is to obtain a significant speed advantage by using `{collapse}` instead of `{dplyr}` due to the size of data, number of groups, and number of times I need to perform this operation, but it looks like switching the above to `fgroup_by()` and `fsummarise()` results in an error, and as you point out, naming the functions may lose the speed advantage?

**Comment by SebKrantz** [comment]
This should do the job, at least the development version of collapse which you can install using `install.packages("collapse", repos = "https://fastverse.r-universe.dev")` has `.names = "flip"` which you can use to achieve the reverse renaming. In general, collapse is a little bit simpler than dplyr, e.g. I don't support lamda expressions or glue, but the documentation is pretty detailed and should answer many questions on how to do things. 

```
mtcars |> 
  fgroup_by(cyl) |> 
  fsummarise(
    across(
      .cols = c(mpg, disp, hp),
      .fns = list(
        "mean"  = fmean,
        "stdev" = fsd,
        "eff"   = neff
      ),
      w = wt, 
      .names = "flip"
    )
  )
```

**Comment by ttrodrigz** [comment]
Thanks again, I appreciate the help!
