### ISSUE TITLE
(Feature request) Collapse version of `duplicated()`

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#373]
Hi, I was wondering if there was scope for a collapse version of base R's `duplicated()`? Thanks!

**Comment by SebKrantz** [comment]
Thanks, yeah I can do this, but this is already quite easy to do yourself, all the ingredients are there. This function will work for atomic vectors and data frames. 

```r
library(collapse)
fduplicated <- function(x) {
  g = group(x, starts = TRUE)
  starts = attr(g, "starts")
  if(length(starts) == length(g)) return(alloc(FALSE, length(g)))
  dup = alloc(TRUE, length(g))
  dup[starts] = FALSE
  dup
}
```

**Comment by NicChr** [comment]
Thanks, that works perfectly!

**Comment by SebKrantz** [comment]
I just added it. In one hour you will be able to install collapse 1.9.3 from r-universe using `install.packages("collapse", repos = "https://fastverse.r-universe.dev")`.
