### ISSUE TITLE
Feature request: named vector for recode_char

### ISSUE THREAD

**Issue by egoipse** [SebKrantz/collapse#378]
Hi,

I just discovered collapse and am delighted by its speed and intuitive semantic. I'm definitelly adopting as my new R framework. My multi-multi-multi core work station is flying with its lots of threads and  set_collapse( nthreads = a_lot_of_threads).

Just a request in case you find it useful: diplyr's `recode` allows to use a named character vector to execute the recoding. As states its docummentation, it's possible to do it like this:

```
# Use a named character vector for unquote splicing with !!!
level_key <- c(a = "apple", b = "banana", c = "carrot")
recode(char_vec, !!!level_key)
```
It would be a nice feature if we could do that with collapse's `recode_char`.

Thanks for the great and extremally useful work.

Regards!

**Comment by SebKrantz** [comment]
Thanks, note though that only some statistical functions in *collapse* are multithreaded, not the whole software (many algorithms also cannot be multithreaded). Regarding your suggestion, I can do it, but if you want performance and multithreading I suggest to use `kit::vswitch()` (part of the core [fastverse](https://github.com/fastverse/fastverse)).

**Comment by egoipse** [comment]
Thanks a lot. `kit::vswitch()` did the job.
