### ISSUE TITLE
descr function outputs incorrect datetime

### ISSUE THREAD

**Issue by cdignam-chwy** [SebKrantz/collapse#392]
Using descr() function on dataframe appears to recalculate datetime (POSIXct) values to local time. The statistical min / max dates are therefore incorrect.

**Comment by SebKrantz** [comment]
Hi, thanks for flagging this. I think the issue is fixed now. You can install *collapse* 1.9.4 from r-universe to check: 

```r
install.packages("collapse", repos = "https://fastverse.r-universe.dev")
```
