### ISSUE TITLE
`funique()` error when data frame has 0 rows

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#406]
Hi, I noticed that `collapse::funique()` produces an error when the data has 0 rows and `sort = TRUE`.

``` r
packageVersion("collapse")
#> [1] '1.9.3'
collapse::funique(dplyr::slice(iris, 0L), sort = TRUE)
#> Error in if ((use.group && length(o) == attr(o, "N.groups")) || (!use.group && : missing value where TRUE/FALSE needed
```

<sup>Created on 2023-04-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, I'm just pushing out the fix.
