### ISSUE TITLE
`gsplit`/`rsplit`'s `NA` handling

### ISSUE THREAD

**Issue by tappek** [SebKrantz/collapse#413]
Is there a way to make `NA` handling in splitting variable like in base R's `split` for `gsplit` and `rsplit` (drop values to be split by `NA`)?

Did I overlook something? It is easy to drop `NA`s afterwards but I thought of the collapse versions as almost drop-in replacements for `split`. What do you think?

```
id   <- rep(1:3,each=3)
id_na <- id
id_na[c(2, 6)] <- NA
time <- rep(1:3,3)

split(time, id_na) # list with 3 elements
#> $`1`
#> [1] 1 3
#> 
#> $`2`
#> [1] 1 2
#> 
#> $`3`
#> [1] 1 2 3
collapse::rsplit(time, id_na) # list with 4 elements
#> $`1`
#> [1] 1 3
#> 
#> $`2`
#> [1] 1 2
#> 
#> $`3`
#> [1] 1 2 3
#> 
#> $<NA>
#> [1] 2 3
collapse::gsplit(time, id_na, use.g.names = TRUE) # list with 4 elements
#> $`1`
#> [1] 1 3
#> 
#> $`2`
#> [1] 1 2
#> 
#> $`3`
#> [1] 1 2 3
#> 
#> $<NA>
#> [1] 2 3


collapse::gsplit(time, id_na, use.g.names = TRUE, na.last = TRUE)  # list with 4 elements
#> $`1`
#> [1] 1 3
#> 
#> $`2`
#> [1] 1 2
#> 
#> $`3`
#> [1] 1 2 3
#> 
#> $<NA>
#> [1] 2 3
collapse::gsplit(time, id_na, use.g.names = TRUE, na.last = FALSE) # list with 4 elements
#> $<NA>
#> [1] 2 3
#> 
#> $`1`
#> [1] 1 3
#> 
#> $`2`
#> [1] 1 2
#> 
#> $`3`
#> [1] 1 2 3
```

**Comment by SebKrantz** [comment]
Hi, the short answer I'm afraid is no. `gsplit()` is based on 'GRP' objects (it converts your factor using `GRP.factor`). 'GRP' objects are multivariate and do not support the concept of missing values (there is no NA group). So you'd have to remove missing values from your data and factors beforehand. The `whichNA()` function can help with that.

**Comment by tappek** [comment]
Thank you for the swift reply!
