### ISSUE TITLE
`qDF()` and `qDT()` on 0-column data frames

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#415]
Hi, I noticed that `qDF()` and `qDT()` produce an error when used on 0-column data frames. 

``` r
collapse::qDF(iris[0, 0])
#> Error in X[[1L]]: subscript out of bounds
collapse::qDT(iris[0, 0])
#> Error in X[[1L]]: subscript out of bounds
```

<sup>Created on 2023-04-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, I'll try to fix this soon. Btw. nice work on timeplyr. I looked at some of the code. I have one remark: have you noticed the `TRA` argument to fast statistical functions? It seems to me you are doing too much in those `gsum` etc. functions i.e. `gsum` defined as 

```r
gsum <- function(x, g = NULL, na.rm = TRUE, ...) {
    collapse::fsum(x, g = g, use.g.names = FALSE, na.rm = na.rm, TRA = "replace_fill", ...)
}
```

should be identical to your implementation (even if `g` is not a 'GRP' object it will be coerced to one). For cases not involving fast statistical functions, *collapse* also offers function `greorder` to expand output again, which also avoids a rather expensive radix sort.

**Comment by NicChr** [comment]
Thanks, just tried your suggestion and it worked perfectly! 
Also I couldn't have implemented parts of `timeplyr` without the blazing fast `collapse` functions. 😃

**Comment by SebKrantz** [comment]
Sure. Just fixed the issue. A qualifier regarding the end of my remark which was partly wrong: `TRA()` is the function you could consider using even without the fast statistical functions e.g. `TRA(x, BY(x, g, sum), "replace_fill", g)` is the same as `fsum(x, g, TRA = "replace_fill")`, but the latter is faster of course and more convenient. `greorder()` should only be used if the result is already of the right length e.g. if `y = unlist(lapply(gsplit(x, g), identity))` then `identical(greorder(y, g), x)`.
