### ISSUE TITLE
Request: collap() to allow non-wide return for single FUN

### ISSUE THREAD

**Issue by ummel** [SebKrantz/collapse#419]
collap() returns non-wide output when aggregating with multiple functions:

`collap(wlddev, ~ country + decade, custom = list(fmean = 10:11, fmode = 10), return = "long")`

But fails (with somewhat different error messages) when aggregating with single function:

`collap(wlddev, ~ country + decade, custom = list(fmean = 10:11), return = "long")`
return options other than 'wide' are only meaningful if multiple functions are used!
Error in collap(wlddev, ~country + decade, custom = list(fmean = 10:11),  : 
  list passed to setcolorder has no names

`collap(wlddev, ~ country + decade, cols = is.numeric, return = "long")`
return options other than 'wide' are only meaningful if multiple functions are used!
Error in collap(wlddev, ~country + decade, cols = is.numeric, return = "long") : 
  object 'o' not found

I don't see any fundamental reason that non-wide output is _incompatible_ with a single aggregation function. Yes, the "Function" column is not "meaningful" in that case -- but from standpoint of flexible programming it is preferable to allow non-wide output across diverse use cases rather throw an error.

**Comment by SebKrantz** [comment]
Ok, thanks, I'll see what can be done here...

**Comment by SebKrantz** [comment]
Also fixed now.
