### ISSUE TITLE
Bug: collap(..., return = "long") sometimes returns integer for "Function" column

### ISSUE THREAD

**Issue by ummel** [SebKrantz/collapse#420]
The following works as expected; returns "fmean" or "fmode" in the output Function column:

`head(collap(wlddev, ~ country, custom = list(fmean = 9:10, fmode = 10), return = "long"))`

  Function        country      PCGDP   LIFEEX
1    fmean    Afghanistan   483.8351 49.19717
2    fmean        Albania  2819.2400 71.68027
3    fmean        Algeria  3532.2714 63.56290
4    fmean American Samoa 10071.0659       NA
5    fmean        Andorra 40083.0911       NA
6    fmean         Angola  2887.6879 46.75805

But this returns integer (1 or 2) in the output Function column:

`head(collap(wlddev, ~ country, custom = list(fmean = 9, fmode = 10), return = "long"))`

  Function        country      PCGDP LIFEEX
1        1    Afghanistan   483.8351     NA
2        1        Albania  2819.2400     NA
3        1        Algeria  3532.2714     NA
4        1 American Samoa 10071.0659     NA
5        1        Andorra 40083.0911     NA
6        1         Angola  2887.6879     NA

Looks like an index isn't being transformed to the correct function name. I _think_ this may only occur when there is no overlap in the 'custom' columns specified across functions.

**Comment by SebKrantz** [comment]
Thanks, yeah the return argument as it stands now was really conceived for cases where we apply multiple functions to the same columns. I'll see though how I can make it more flexible.

**Comment by SebKrantz** [comment]
I just fixed this. The problem was with the `give.names = "auto"` default, setting `give.names = TRUE` gives what you want, but now in the development branch also with `"auto"`.
