### ISSUE TITLE
Question on sort order of fmean() et al.

### ISSUE THREAD

**Issue by mayer79** [SebKrantz/collapse#424]
Awesome package! 

Is it correct that `fmean()` (and similar) applied to vectors, matrices, data.frames always return the result sorted by each grouping column? (I am asking because I do not want to parse the row names.)

**Comment by SebKrantz** [comment]
Yes, the default for all grouped operations is `sort = TRUE`. You can change this directly in `GRP()` and dependent functions like `collap()` or `fgroup_by()` e.g. `g = GRP(vec, sort = FALSE); fmean(x, g)`. You can also globally change it in all functions (including internal grouping) using `set_collapse(sort = FALSE)`, such that `fmean(x, vec)` gives the same as the above.

**Comment by mayer79** [comment]
Ahhh, thanks for clarification!
