### ISSUE TITLE
Feature Request: frank

### ISSUE THREAD

**Issue by Fredo-XVII** [SebKrantz/collapse#426]
Hello!

I have been translating a function from dplyr to collapse as a way to learn collapse.  I searched your documentation but I could not find any reference for rank.  I will paste the code and expectation below.  

Current dplyr::
```
> DUPES_LIST %>%
+       dplyr::inner_join(CONTROL_STR_LIST) %>%
+       dplyr::group_by(.data$CONTROL) %>%
+       dplyr::mutate(rank = dplyr::min_rank(.data$DIST_Q)) %>% head()
Joining, by = "CONTROL"
# A tibble: 4 x 6
# Groups:   CONTROL [2]
  CONTROL       control_cnt TEST           DIST_Q GROUP  rank
  <fct>               <int> <fct>           <dbl> <int> <int>
1 Massachusetts           2 New Jersey      0.798     3     1
2 Massachusetts           2 Rhode Island    0.944     5     2
3 Mississippi             2 North Carolina  1.18      4     2
4 Mississippi             2 South Carolina  0.787     6     1
```

I am stuck here on the fst version:
```
    rank_dupes_fst <- DUPES_LIST_fst %>%
      dplyr::inner_join(CONTROL_STR_LIST_fst) %>%
      collapse::fgroup_by(CONTROL) %>% 
```

This is the code that I have currently translating to collapse:
https://github.com/Fredo-XVII/TestContR/blob/master/R/match_numeric_fst.R

Thank you,

Alfredo

**Comment by SebKrantz** [comment]
Hi, so in general, *collapse* is not a comprehensive data manipulation package. It offers *advanced and fast* data transformation so operations either not supported by other packages or implemented in a faster way than other packages. I created the *fastverse* package particularly because *collapse* works well with *data.table* and also *kit*, which have many complimentary functions. In your case, `collapse::fmutate()` together with `data.table::frank(..., ties.method = "min")` should do the job. So in conclusion, you'll be able to do a complete translation of your *tidyverse* / *dplyr* code using the *fastverse*, but not using *collapse* alone.

**Comment by Fredo-XVII** [comment]
Interesting. I guess that I didn't get that from my reading on collapse.  Could I then ask a follow up question.  Could you give me an example when you would use collapse?  What are the use cases?

I have only used collapse more when doing some basic summary stats, but I feel like it could be used for more.  I have never heard of kit, so I will look into that.  I really like data.table, but I struggle with the syntax.  Every time I want to use it because of data constraints, I have to re-learn how to use it.

**Comment by SebKrantz** [comment]
Ok, so *collapse* does actually provide a lot of functions and operations, as you can see from eyeballing the [documentation](https://sebkrantz.github.io/collapse/reference/index.html). The main things is does not do it joins and reshaping of data. *data.table* also has a lot of [functions and operations](https://rdatatable.gitlab.io/data.table/reference/index.html). You can use *collapse* together with *data.table* without using *data.table* syntax. This is what I often do. An example is given in my recent [blog post](https://sebkrantz.github.io/Rblog/2023/04/12/collapse-and-the-fastverse-reflecting-the-past-present-and-future/) where I compute geospatial GINI’s for South Africa. Alternatively you can of course also mix *collapse* with *dplyr* as you have been doing. The package works seamlessly with both data.table’s and tibble’s. Using it with data.table as encouraged through the *fastverse* of course results in overall very fast programs.

**Comment by SebKrantz** [comment]
The [cheatsheet](https://github.com/SebKrantz/collapse#cheatsheet-v188) also gives a very nice overview of collapse’s capabilities + small examples.

**Comment by Fredo-XVII** [comment]
Thanks for the info. I'll definitely check it the blog.  After reading a blog on the vctrs package, I realized that I could build Markdown docs much faster if I used vctrs. Then I thought about collapse and thinking it would be even faster.  
I'll keep experimenting.  

Thanks again!
