### ISSUE TITLE
Custom function on nested data, say a regression

### ISSUE THREAD

**Issue by statzhero** [SebKrantz/collapse#431]
Is it possible to do custom grouped operations beyond `BY` column-wise operations? I imagine like a regression model on the nested (grouped) data. As an example of what I have in mind, see this: 

```r
mtcars |> 
  dplyr::group_by(cyl) |>  
  tidyr::nest() |> 
  dplyr::mutate(data_m = lapply(data, as.matrix)) |> 
  dplyr::mutate(model = lapply(data_m, \(x) RcppEigen::fastLmPure(X = x[, c("disp", "hp")], y = x[, "mpg"])))
```

**Comment by SebKrantz** [comment]
Yes, *collapse* just doesn't have `nest_by()`, but you can do
```r
mtcars |> gby(cyl) |> 
    smr(list(data = list(slt(.data, -cyl)))) |> 
    mtt(data_m = lapply(data, qM)) |> 
    mtt(model = lapply(data_m, \(x) RcppEigen::fastLmPure(X = x[, c("disp", "hp")], y = x[, "mpg"]))) 
```

A more *collapse* - like way to do this would be

```r
mtcars |> gby(cyl) |> 
  smr(models = list(flm(mpg ~ disp + hp, method = "eigen", return.raw = TRUE)))
```

**Comment by SebKrantz** [comment]
Also see ?across with the .apply = FALSE argument. That’s a good option if you have a predefined function that you eant to apply to a data frame consisting of certain columns.

**Comment by statzhero** [comment]
Top notch, as always. Thank you!

**Comment by statzhero** [comment]
FWIW, I thought the `rapply2d` could also work as per your cheatsheet but I couldn't quite figure out the trick.

```r
# fails even if dispatched with the .formula method
mtcars |> rsplit(mpg + hp + disp ~ cyl) |> 
  rapply2d(RcppEigen::fastLm, formula = mpg ~ .)
```

**Comment by SebKrantz** [comment]
That seems to be an issue with `fastLm` It works if you use `flm()`, which is a minimal wrapper around different linear fitting methods: 

```r
mtcars |> rsplit(mpg + hp + disp ~ cyl) |> 
 lapply(flm, formula = mpg ~ ., method = "eigen", return.raw = TRUE)
```
Since the list is not nested, `rapply2d()` is not needed here either.
