### ISSUE TITLE
Session crashing when using setv on character vector.

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#434]
Hi, my R session crashes when I run the below code a few times. 
I'm essentially trying to expand the group names to the length of the data, similar to `GRPN(expand = TRUE)` but
I'm not sure why my R session aborts. I've tried on a separate machine with similar results. 

```{r}
  set.seed(91301125)
  df <- data.frame(group = sample.int(10^5, 10^5, TRUE))
  g <- collapse::GRP(df)
  g_names <- collapse::GRPnames(g, force.char = TRUE)
  GRP_loc <- collapse::gsplit(NULL, g = g)
  out <- character(length(g))
  for (i in seq_along(GRP_loc)){
    collapse::setv(out, GRP_loc[[i]], g_names[i], vind1 = TRUE)
  }
```

I don't get any crashing when using integers:

```{r}
  set.seed(91301125)
  df <- data.frame(group = sample.int(10^5, 10^5, TRUE))
  g <- collapse::GRP(df)
  g_names <- collapse::GRPnames(g, force.char = FALSE)
  GRP_loc <- collapse::gsplit(NULL, g = g)
  out <- integer(length(g))
  for (i in seq_along(GRP_loc)){
    collapse::setv(out, GRP_loc[[i]], g_names[i], vind1 = TRUE)
  }
```

**Comment by SebKrantz** [comment]
Thanks, I'll look into this. The efficient way to do this would however be `g_names[g$group.id]` instead of using a for loop.

**Comment by SebKrantz** [comment]
If you can check this for me still using the fix I just pushed to master. I am unable to reproduce the issue on the M1, but I think it is a protect bug.
