### ISSUE TITLE
Search bar for website

### ISSUE THREAD

**Issue by grantmcdermott** [SebKrantz/collapse#439]
Hi Sebastian.

I can see that you _almost_ added Bootstrap 5 support to the pkgdown website in https://github.com/SebKrantz/collapse/commit/cfa11de3bde13036c5ff46ce78f4b36f7e8f99f0#diff-f5f791eb2285a738ec729c44088e49a60ddf355eb479fb1fb5df7fcea4fea2e8 

Is there are a particular reason why you opted out? My main reason for asking is that I'd love the additional search bar functionality that comes bundled with the Bootstrap 5 update. The `collapse` website and vignettes are extremely well organized. But there is a _lot_ of content, which can make it tricky to find specific items.

**Comment by SebKrantz** [comment]
Hi Grant, I think back then I found the text too large. But I'll look into this again when I push out the next update. I've started working on *collapse* 2.0, to be release hopefully within a few months time. For this a new website look might indeed be a good idea.

**Comment by grantmcdermott** [comment]
Super, thanks for the update. I guess we can keep this open until then. Looking forward to the v2.0 release!

**Comment by grantmcdermott** [comment]
The new website looks ace! 

Congratulations on the v2.0.0 release, Seb. Loving the addition of joins, pivot functions, etc. There’s so much to like here.

**Comment by SebKrantz** [comment]
Thanks! By the way, I tried to look for a nice code theme for the documentation that would provide some contrast. The "ayu-mirage" theme by bootswatch applied now looks decent, but I like even better the theme now used by Rstudio with a dark theme. 

<img width="724" alt="Screenshot 2023-10-12 at 08 58 32" src="https://github.com/SebKrantz/collapse/assets/48053842/ce5aca00-4c61-4ad3-911b-e80a1459a2af">

Do you by any chance have any idea where this is coming from?
