### ISSUE TITLE
naming of fmutate columns that depend on `...` arguments

### ISSUE THREAD

**Issue by swhalemwo** [SebKrantz/collapse#442]
I'm trying to create lagged versions at different lags of a number of variables, and would like to have the resulting variables names in the format `vrblname_lagN` (e.g. "PCDGP_lag1").

```
rel_cols <- c("PCGDP", "LIFEEX", "GINI", "ODA")
dt_wlddev <- qDT(wlddev)

dt_wlddev %>% fmutate(across(rel_cols, L, n = 1:3))

dt_wlddev %>% ftransformv(rel_cols, L, n = 1:3, apply =F)
```

Both produce variable names in the format "LN.vrblname" (e.g. "L1.PCDGP"). I saw that in `across`, `.names` can take a function with two arguments for colum and function names, but I can't see how to use this to create the variable names in the format that I want.

**Comment by SebKrantz** [comment]
Hi, so with functions that create multiple columns this is indeed tricky. The names `L1.` etc. are created by `L()` itself e.g. `L(mtcars, 1:3)`. It is not sensible to parse arguments passed to `across()` functions and somehow use them to generate custom variable names. So the only option you have here is to either rename columns ex-post, or use something like 

```r
dt_wlddev %>% fmutate(across(rel_cols, list(lag1 = L), n = 1, .names = TRUE), 
                                          across(rel_cols, list(lag2 = L), n = 2, .names = TRUE), 
                                          across(rel_cols, list(lag3 = L), n = 3, .names = TRUE))
```
Or 

```r
dt_wlddev %>% add_vars(
  get_vars(., rel_cols) %>% flag(1) %>% add_stub("_lag1", FALSE),
  get_vars(., rel_cols) %>% flag(2) %>% add_stub("_lag2", FALSE),
  get_vars(., rel_cols) %>% flag(3) %>% add_stub("_lag3", FALSE)
)
```
These are, unfortunately, less efficient than a single call to `flag()`, but that is the price you have to pay here for custom names.

**Comment by swhalemwo** [comment]
thanks for the fast reply! I think I'll go for renaming afterwards then since this allows better control over the number of lags. thanks for your help :)
