### ISSUE TITLE
fmedian not recognising tie

### ISSUE THREAD

**Issue by jistria** [SebKrantz/collapse#448]
I have observed an unexpected result when using `fmedian` demonstrated below. Here the weights are distributed evenly between the sets `c(1, 2)` and `c(3, 4)` and hence `2` and `3` should tie.

```R
x <- c(1, 2, 3, 4)
w <- c(2.5, 2.4, 3.8, 1.1)

fmedian(x, w = w, ties = "mean") # Expecting 2.5
## [1] 2
fmedian(x, w = w, ties = "min")  # Expecting 2
## [1] 2
fmedian(x, w = w, ties = "max")  # Expecting 3
## [1] 2
```

If I make a slight tweak to the weights, but maintain the tie I get a different result.

```R
x <- c(1, 2, 3, 4)
w <- c(2.5, 2.4, 3.7, 1.2)

fmedian(x, w = w, ties = "mean") # Expecting 2.5
## [1] 2.5
fmedian(x, w = w, ties = "min")  # Expecting 2
## [1] 2
fmedian(x, w = w, ties = "max")  # Expecting 3
## [1] 3
```

Is this the result of a bug, or do I misunderstand something?

I observe this result when using the CRAN version 1.9.6 and the current development version 1.9.6.9500. Here is my session info when using the latter:

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8    LC_MONETARY=English_Australia.utf8 LC_NUMERIC=C                       LC_TIME=English_Australia.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] collapse_1.9.6.9500

loaded via a namespace (and not attached):
[1] compiler_4.2.0 parallel_4.2.0 tools_4.2.0    Rcpp_1.0.10    renv_1.0.2    
```

Thanks in advance for your time.

**Comment by SebKrantz** [comment]
Thanks, yeah looks like a bug, but I will investigate. Just a general note up front: with weights, quantile based methods make more sense, e.g. `fmedian(x, w = w, ties = "q8")` gives a much more reasonable result.

**Comment by SebKrantz** [comment]
Hi, this was a numeric prevision issue from comparing the cumulative sum of weights with the ideal threshold using `==` between doubles, I've solved this on M1 Mac using a factor `10*.Machine$double.eps` to the ideal threshold and using `<`. Still testing other systems.

**Comment by SebKrantz** [comment]
I regard this issue as resolved.
