### ISSUE TITLE
Strange results with grouping rounded numbers close to zero

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#452]
I'm not really what's going on here but there seem to be conflicting results between base R and the collapse functions after rounding numbers.

When rounding normally distributed values, 0 appears to be counted as 2 distinct groups for most collapse functions 
(except `collapse::qG(x, sort = TRUE)`)

I've attached a reprex for more info.

``` r
options(digits = 22)
set.seed(42)

x <- round(rnorm(1e05))

sort(unique(x))
#> [1] -4 -3 -2 -1  0  1  2  3  4
collapse::funique(x, sort = TRUE)
#>  [1] -4 -3 -2 -1  0  0  1  2  3  4
# sort(x[!collapse::fduplicated(x)])

length(unique(x))
#> [1] 9

attr(collapse::qG(x, sort = TRUE), "N.groups")
#> [1] 9
attr(collapse::qG(x, sort = FALSE), "N.groups")
#> [1] 10

collapse::GRP(x, sort = TRUE)$N.groups
#> [1] 10
attr(collapse::group(x), "N.groups")
#> [1] 10

collapse::fnunique(x)
#> [1] 10
collapse::fndistinct(x)
#> [1] 10
```

<sup>Created on 2023-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

There seem to be roughly equal numbers between the two "zero" groups, which might hint at the fact this is an issue with positive/negative signs being distinguished somewhere.

```{r}
> table(x[collapse::qG(x, sort = FALSE) == 3])

    0 
19115 
> table(x[collapse::qG(x, sort = FALSE) == 4])

    0 
19054 
```

**Comment by SebKrantz** [comment]
Thanks, I'll look into this as I find time, but in general, it is unlikely there is a fix to this. With `sort = TRUE`, collapse uses radix ordering to determine unique values, which basically partical up numbers into sequences of bytes which it sorts. This I guess cannot distinguish between two nearly identical numbers. Hashing on the other hand (used with `sort = FALSE`) compares real numbers with `==`, and thus takes account of even very small deviations.

**Comment by NicChr** [comment]
Thanks, that's useful to know, seems like there's no easy fix.

Wouldn't that also mean that `GRP(x, sort = TRUE)` would use the radix ordering and thus give the same number of groups as `qG(x, sort = TRUE)`?

**Comment by SebKrantz** [comment]
Ok, so actually the problem is not radix sorting, `str(radixorder(x, starts = TRUE))` gives a `"starts"` attribute of length 10. However, in the case of `qG()`, the result is computed as `groupid(x, radixorder(x))`, so it seems that the C++ function groupid, when moving through the data in order, is not able to distinguish two zeros from one another. In general though rounding is problematic. For example using `floor(rnorm(1e5))` or `ceiling(rnorm(1e5))` does not give similar effects. Anyway, I'm not going to figure out why C distinguishes between two types of zeros and C++ doesn't..

**Comment by SebKrantz** [comment]
This issue will not be solved, as it has to do with numeric precision in R. As indicated, I do not recommend using `round()` on vectors used for grouping. `floor()`, `ceiling()`, `trunc()` or `as.integer()` all give better behavior.

**Comment by NicChr** [comment]
Sorry to reopen this issue but thought it might be of interest to add that the issue can be solved (at least on my machine) by adding zero after rounding which is handy as it should be just as efficient as using `base::round()`.

Also, the issue can be seen when using `trunc()` as well as `round()`.

A somewhat simpler reprex..

``` r
round <- function(x, digits = 0, ...){
  base::round(x, digits, ...) + 0
}
trunc <- function(x, ...){
  base::trunc(x, ...) + 0
}

library(collapse)

funique(base::round(c(-0.05, 0.05)))
#> [1] 0 0
funique(base::trunc(c(-0.05, 0.05)))
#> [1] 0 0

funique(round(c(-0.05, 0.05)))
#> [1] 0
funique(trunc(c(-0.05, 0.05)))
#> [1] 0
```

**Comment by NicChr** [comment]
`data.table::rleid()` also suffers from this issue funnily enough.

```{r}
> data.table::rleid(base::round(c(-0.05, 0.05)))
[1] 1 2
> data.table::rleid(round(c(-0.05, 0.05)))
[1] 1 1
```

**Comment by SebKrantz** [comment]
Thank, this is interesting! Not sure exactly what `+` does here, it might be something else than adding a `0` in C. Unfortunately, I don't have time to look further into this right now.
