### ISSUE TITLE
collapse::ss() aborts R

### ISSUE THREAD

**Issue by tony-aw** [SebKrantz/collapse#453]
Hi,

Doing `collapse::ss(x, i = rep(FALSE, nrow(x)), j = rep(FALSE, ncrol(x))` will abort my entire R session.
Similarly, giving empty integer vectors to arguments `i` and `j` also aborts my entire R session.
Explicitly setting argument `check = TRUE` does not change this.
It also does not matter if `x` is a `data.frame`, a `data.table` or a `tibble`, it will always terminate my entire R session.
Not sure if it is relevant, but I'm working in R Studio.

Please fix this. Thank you in advance.

Kind regards,

Tony

**Comment by SebKrantz** [comment]
Thanks, this is already fixed in the development version.
