### ISSUE TITLE
allv returns TRUE when x has zero length.

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#454]
Hi, I use `allv` often as it's really fast and useful. I just noticed that it returns `TRUE` when x is a zero length vector.

I assume this is likely because it's initialised with `TRUE` but has nothing to loop over and hence returns `TRUE` but I think it might make more sense to have a length check so that `FALSE` is returned when x has 0 length.

``` r
collapse::allv(integer(), 100)
#> [1] TRUE
collapse::allv(character(), "a")
#> [1] TRUE
collapse::allNA(numeric())
#> [1] TRUE
collapse::allv(factor(), "b")
#> [1] TRUE
```

Appreciate you looking at this whenever you have a moment, no rush and many thanks. 😃 

<sup>Created on 2023-09-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, I've changed this for `allv()` and `anyv()` as you suggested. For `allNA()` I have not changed it because `all(is.na(numeric()))` returns `TRUE` i.e. empty vectors are regarded as missing.

**Comment by NicChr** [comment]
Thanks, I've been rethinking this one and wonder if a change like this is more code-breaking than I initially considered.
For me personally I find it useful to have `allv(integer())` evaluate to `FALSE` in many situations, but that might not be the case for others. 
Furthermore after reading a bit I realised that the collapse version follows the same convention that base R uses which is ultimately probably more useful.

The other and perhaps more important consideration is that returning an empty logical vector might break a lot of **if**/**else** statements.

Thanks again and happy to hear your thoughts!

**Comment by SebKrantz** [comment]
Thanks, ideally the behavior should be exactly the same as base R. It turns out that `any(character() == letters)` is `FALSE`, and `all(character() == letters)` is `TRUE`. Same with `anyNA(numeric())` and `allNA(numeric())`. I have changed this now accordingly.
