### ISSUE TITLE
Question on settransformv

### ISSUE THREAD

**Issue by caleb-kwon** [SebKrantz/collapse#457]
Hi Sebastian, 

First, thanks so much for this brilliant package. It has been a staple in my workflow and pairs very nicely with `data.table`. Superb documentation as well.

I have a quick question w.r.t using `settransformv` and creating lags. Please see the example below:

```
library(data.table)
library(collapse)

# Create a data.table
dt <- data.table(
  Worker = c("Alice", "Alice", "Alice", "Alice", "Alice", "Alice", 
             "Bob", "Bob", "Bob", "Bob", "Bob", "Bob",
             "Charlie", "Charlie", "Charlie", "Charlie", "Charlie", "Charlie"),
  Store = c("Store1", "Store1", "Store1", "Store2", "Store2", "Store2",
            "Store1", "Store1", "Store2", "Store2", "Store3", "Store3",
            "Store2", "Store2", "Store3", "Store3", "Store3", "Store3"),
  Week = c(1, 3, 4, 2, 3, 5,
           1, 2, 3, 4, 2, 3,
           1, 2, 3, 5, 6, 7),
  Hours_Worked = c(10, 20, 15, 25, 30, 35,
                   40, 45, 15, 20, 25, 30,
                   35, 40, 20, 25, 30, 35)
)

# Set keys for efficient joining and reordering
setkey(dt, Worker, Store, Week)


```
In this context, there are multiple workers across stores. A worker can be at more than one store. My objective is to create lags and leads quickly (the real dataset is very large). 

One way is to do the following, which works nicely:

```
dt <- L(dt, n = 1, by = ~ Worker + Store, t = ~ Week, cols = c("Hours_Worked"))
```
So here, lags are created after grouping Workers and Stores. This works very nicely. However, this approach drops columns that are not part of this particular line. 

So, when I try to do this using settransformv to keep all columns, I seem to be running into issues, as none of the below work:

```
settransformv(dt, "Hours_Worked", flag, 1,  gby(Worker,Store), Week, apply = FALSE)
settransformv(dt, "Hours_Worked", flag, 1,  ~ Worker + Store, Week, apply = FALSE)
```
However, this approach works well:
```
dt |> 
  fgroup_by(Worker, Store) |>
  fmutate(lag = flag(Hours_Worked, t = Week))
```
I've fiddled around a few more and read the docs, but I am unsure if it is possible to group by with multiple columns. Naturally, there are alternative ways, such as concatenating Workers and Stores to have a unique identifier. But I was wondering if, more broadly, settransformv can handle multiple groups (through columns).

Thanks!

**Comment by SebKrantz** [comment]
Hi, thanks. So the `g`argument to `flag` and fast statistical functions only accepts vectors or lists /data.frame's with grouping variables. `by` additionally supports formulas of variables in the data frame. `flag` only has `g`, so you need to do: 

```r
settransformv(dt, "Hours_Worked", flag, 1, list(Worker,Store), Week, apply = FALSE)
```
Other options for muliple columns are 

```r
dt |> 
  fgroup_by(Worker, Store) |>
  fmutate(across(Hours_Worked, flag, t = Week)) |>
  fungroup()
```
or 
```r
dt |> 
  findex_by(Worker, Store, Week) |>
  fmutate(across(Hours_Worked, flag)) |>
  unindex()
```
Hope that helps.
