### ISSUE TITLE
Issue counting rows

### ISSUE THREAD

**Issue by roaldarbol** [SebKrantz/collapse#477]
Hi! Really excited to have discovered this library - I work with large data sets and I'm sure this will provide significant speed-ups, so I'll begin changing over and provide some feedback as I go along. So thanks for the effort developing `collapse`!
The first issue I've come across is not being able to count a number of rows in `fsummarise`. I've tried a few different things:

I've tried converting the current method, using `n()`, and also with `fnrow()` and `fnobs()` to no avail. Am I missing something trivial or is it a bug?
``` r
library(tidyverse)
library(collapse)
#> collapse 2.0.3, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:lubridate':
#> 
#>     is.Date
#> The following object is masked from 'package:stats':
#> 
#>     D
data(starwars)

# Current implementation
starwars |>
  group_by(sex) |>
  summarise(count = n())
#> # A tibble: 5 × 2
#>   sex            count
#>   <chr>          <int>
#> 1 female            16
#> 2 hermaphroditic     1
#> 3 male              60
#> 4 none               6
#> 5 <NA>               4

# Using various collapse combinations
starwars |>
  fgroup_by(sex) |>
  fsummarise(count = n())
#> Error in x[[2L]]: subscript out of bounds
starwars |>
  fgroup_by(sex) |>
  fsummarise(count = fnrow())
#> Error in x[[2L]]: subscript out of bounds
starwars |>
  fsummarise(count = fnrow())
#> Error in fnrow(): argument "X" is missing, with no default
starwars |>
  fgroup_by(sex) |>
  fsummarise(count = fnobs())
#> Error in fnobs.default(g = .g_, use.g.names = FALSE): argument "x" is missing, with no default
starwars |>
  fsummarise(count = fnobs())
#> Error in fnobs.default(): argument "x" is missing, with no default
```

<sup>Created on 2023-10-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Hi, use `GRPN()`, or if you use masking with `set_collapse(mask = "special")` or `set_collapse(mask = "all")`, you can use `n()`. If you're coming from dplyr something like `set_collapse(mask = c("manip", "helper", "special"))` or `set_collapse(mask = "all")` should get you started without much change of syntax.

**Comment by roaldarbol** [comment]
Brilliant, seems to work well - thanks for the quick feedback! How do you deal with `group_by(var, .add = TRUE)`? That seems to fail my pipeline now? (Don't know if it's worthy of it's own issue...)

**Comment by SebKrantz** [comment]
ok, so in *collapse* groupings cannot be modified, this is, in my view, a redundant feature. *collapse* rather supports different ways to group data, including ad-hoc grouping for data transformations available through the `g` argument to many statistical functions. But yeah, once you've grouped a frame, that's what you got, you need to ungroup and regroup it to change.

**Comment by roaldarbol** [comment]
No worries - good to know. Thanks again for the quick feedback, appreciate it!
