### ISSUE TITLE
Cheat sheet mentions `fmatch` but no such function is exported by `collapse`

### ISSUE THREAD

**Issue by orgadish** [SebKrantz/collapse#480]
The [cheat sheet](https://raw.githubusercontent.com/SebKrantz/collapse/master/misc/collapse%20cheat%20sheet/collapse_cheat_sheet.pdf) mentions `fmatch` and `%[!][i][in%` but I could not find such functions in the package.

**Comment by SebKrantz** [comment]
v2.0 and onwards does export fmatch `?fmatch`.
