### ISSUE TITLE
Error when trying to install collapse from source

### ISSUE THREAD

**Issue by mhwachter** [SebKrantz/collapse#484]
Hi, first of all thank you for this amazing package!
When trying to install it from source I ran into the following error message:

> Error: Laden von Paket oder Namensraum für ‘collapse’ in dyn.load(file, DLLpath = DLLpath, ...): fehlgeschlagen
 kann shared object '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/00LOCK-collapse/00new/collapse/libs/collapse.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/00LOCK-collapse/00new/collapse/libs/collapse.so, 0x0006): symbol not found in flat namespace '___kmpc_end_reduce_nowait'

Specs:
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1
Collapse 2.0.3

I followed the instructions for OpenMP [here](https://mac.r-project.org/openmp/) and tried to compile it with
`PKG_CPPFLAGS='-Xclang -fopenmp' PKG_LIBS=-lomp R CMD INSTALL collapse_2.0.3.tar.gz`

There are also two warning messages

> data.table_subset.c:234:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
      PARLOOP(NA_CPLX);
      ^
data.table_subset.c:234:7: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
2 warnings generated.

**Comment by SebKrantz** [comment]
Hi, so I'm not sure this information is helpful. But I'm using an M1 Mac and collapse is working well here, including OpenMP. To compile with OpenMP, you need to install the OpenMP distribution for Mac prepared by CRAN Team, and create an .R/Makevars file with the flags. Full set of instructions: 

Enabling OpenMP on Mac: https://mac.r-project.org/openmp/
In particular, open terminal, run these two lines: 

    curl -O https: //mac.r-project.org/openmp/openmp-12.0.1-darwin20-Release.tar.gz (Maybe there is a newer version)
    sudo tar fvxz openmp-12.0.1-darwin20-Release.tar.gz -C /

Then create a folder called .R in the user directory and inside it a file called Makevars e.g. ~/.R/Makevars. In that file place the following two lines:
     CPPFLAGS += -Xclang -fopenmp
     LDFLAGS += -lomp

From the Mac terminal you can do this using
    cd ~
    mkdir .R
    nano .R/Makevars

Save and restart R, then install collapse from source or r-universe, using e.g. 
    install.packages("collapse", repos = "https://fastverse.r-universe.dev/")

**Comment by SebKrantz** [comment]
And the warnings are ok. I also get them. Basically saving that operations on R complex vectors cannot be vectorized by OpeMP SIMD instructions.

**Comment by mhwachter** [comment]
After creating the Makevars file it worked without any issues.
Thanks a lot!
