### ISSUE TITLE
SD changes when `higher = TRUE` in `qsu()`

### ISSUE THREAD

**Issue by randrescastaneda** [SebKrantz/collapse#490]
First of all, thank you so much for this amazing package. `collapse` is now the most important package in all my projects.
 
I think I found a bug in `qsu()`. When the option `higher = TRUE` is implemented, the values of the standard deviation change, when they should not. Please find below the code that replicates the issue. 

Thanks. 

``` r
library(fastverse)
#> -- [1mAttaching packages[22m --------------------------------------- [38;5;33mfastverse[39m 0.3.1 --
#> [38;5;33mv[39m [38;5;198mdata.table[39m 1.14.8     [38;5;33mv[39m [38;5;198mkit       [39m 0.0.14
#> [38;5;33mv[39m [38;5;198mmagrittr  [39m 2.0.3      [38;5;33mv[39m [38;5;198mcollapse  [39m 2.0.5


higher_false <-
  qsu(wlddev,
      by = PCGDP ~ region + year,
      w  = wlddev$POP)   |>
  as.data.frame() |> 
  qDT() |> 
  head()

higher_true <-
  qsu(wlddev,
      by = PCGDP ~ region + year,
      w  = wlddev$POP,
      higher = TRUE)  |>
  as.data.frame() |> 
  qDT() |> 
  head()


waldo::compare(higher_false$SD, higher_true$SD)
#> `old`:     3080     3307     3477     3684     3994     4152
#> `new`: 41220492 45697844 49103571 52550920 57645148 60227267
```

<sup>Created on 2023-11-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks a lot, and yes this is a bug! I will investigate.

**Comment by SebKrantz** [comment]
Thanks for flagging this. I have fixed this now and added a note to the NEWS about it (https://github.com/SebKrantz/collapse/blob/master/NEWS.md). I hope to release a minor update to CRAN early next week. The GitHub/R-universe version 2.0.6 has the fix.

**Comment by randrescastaneda** [comment]
This is awesome. Thank you so much! 
Best,
