### ISSUE TITLE
fmutate

### ISSUE THREAD

**Issue by Steviey** [SebKrantz/collapse#495]
while

```
btsGr1NameProb1  <-as.name(paste0('schnackel',type,'_Q',grId,'_W',myWin))
                    
ySrc <-ySrc %>% dplyr::mutate(
	!!btsGr1NameProb1:=topsProb3[1]
)

```
would work, but not:
```

ySrc <-ySrc %>% collapse::fmutate(
	!!btsGr1NameProb1:=topsProb3[1]
)
```

Because of a data.table error.
I'm wondering how we can use non-standard-evaluation in collapse.

**Comment by SebKrantz** [comment]
Short answer: *collapse* is built off base R, and the usual way to do NSE there is via `eval(substitute())`. In this case that is tedious though, so I think a better way is to either create the list and pass it to `ftransform()` e.g. 

```r
l <- list(ySrc$topsProb3[1])
names(l) <- btsGr1NameProb1

ySrc |> ftransform(l)
```
(In this particular case just using `ySrc[[btsGr1NameProb1]] <- ySrc$topsProb3[1]` seems easier. 

or, perhaps more what you are looking for, use `frename` with `.nse = FALSE`. e.g. 

```r
ySrc |> fmutate(tmp = opsProb3[1]) |> frename(tmp = btsGr1NameProb1, .nse = FALSE)
```

**Comment by Steviey** [comment]
Ah wunderbar! Vielen Dank.
