### ISSUE TITLE
Incorrect kurtosis in descr

### ISSUE THREAD

**Issue by davidbudzynski** [SebKrantz/collapse#500]
I noticed that Kurtosis values from `collapse::descr()` differ from `psych::describe()`. 

```
> collapse::descr(mtcars$cyl)
Dataset: cyl, 1 Variables, N = 32
---------------------------------------------------------------------------------------------
cyl (numeric): 
Statistics
   N  Ndist  Mean    SD  Min  Max   Skew  Kurt
  32      3  6.19  1.79    4    8  -0.18  1.32
Quantiles
  1%  5%  10%  25%  50%  75%  90%  95%  99%
   4   4    4    4    6    8    8    8    8
---------------------------------------------------------------------------------------------
> psych::describe(mtcars$cyl)
   vars  n mean   sd median trimmed  mad min max range  skew kurtosis   se
X1    1 32 6.19 1.79      6    6.23 2.97   4   8     4 -0.17    -1.76 0.32
```

I know that the `psych `package uses `e1071::kurtosis()` implementation which is based on [Joanes and Gill (1998)](https://rss.onlinelibrary.wiley.com/doi/10.1111/1467-9884.00122), where they outline three different methods of deriving it. Neither of these methods match the kurtosis value from `collapse::descr()`. 

Can you explain why the value I'm getting from your package is so different?

**Comment by SebKrantz** [comment]
The package implements pearsons measure of curtosis as in `moments::kurtosis()`.

**Comment by SebKrantz** [comment]
I am pretty convinced that this is correct, and the e1071 implementation is different.

**Comment by SebKrantz** [comment]
Actually, there is a measure called [Excess Kurtosis](https://en.wikipedia.org/wiki/Kurtosis#Pearson_moments) = kurtosis - 3. (because the kurtosis of a normal distribution is 3). I think this is what you are seeing in psych. It should be labelled there accordingly.

**Comment by davidbudzynski** [comment]
I think this is because psych and e1071 report on "unbiased" estimate of the population kurtosis `b_2 = m_4 / s^4 - 3 = (g_2 + 3) (1 - 1/n)^2 - 3` instead of Pearson's kurtosis which, arguably, is less usefull. It is possible to get Person's kurtosis by transforming it. 

```
> all.equal(psych::kurtosi(mtcars$cyl, type = 1), 
+           moments::kurtosis(mtcars$cyl) - 3)
[1] TRUE
```
It would be worth adding those methods in to get unbiassed kurtosis or at least mention in the docs that the kurtosis from this function is the Pearson's one.

**Comment by SebKrantz** [comment]
Ok, noted. The `collapse` implementation uses [Welford's Online algorithm for higher-order staistics](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Higher-order_statistics) to compute standard deviation, skewness and kurtosis on one pass through the data. Your correct measure would thus have to be calculated in an online fashion, along with the skewness and standard deviation. If you'd like to derive those equations for me I'm happy to implement it, but I don't see this as a priority right now.

**Comment by SebKrantz** [comment]
I just checked that again: in `descr()` it states that it is a wrapper around `qsu()`, `fquantile()` and `fndistinct()`. The documentation of `qsu()` states very clearly how the kurtosis is calculated. So I don't think the docs are a problem. It would be too much to doubly-document all statistical details of the algorithms. Regarding the [unbiased measure](https://en.wikipedia.org/wiki/Kurtosis#Standard_unbiased_estimator), it seems to be simply adding some corrections, but only defined for the excess kurtosis. If you think taking this one and adding 3 gives an unbiased estimate of the populated kurtosis, I can add the correction terms following Welford's Algorithm.

**Comment by davidbudzynski** [comment]
You are acctually right, my bad, I didn't look at `qsu()`. 

> If you think taking this one and adding 3 gives an unbiased estimate of the population kurtosis, I can apply the correction terms following Welford's Algorithm.

Not sure if I understand what you mean by that? 

I generally think that the unbiased measure is more intuitive for people who don't have a degree in statistics (my target "audience"), since at some point they used Excel or leart about it during their university degrees where they were most likely introduced to SPSS. Both of these programs use the unbiased version of this statistic. I have no skin in the game when it comes to this issue since I don't use the package (although it's on my radar and I check the developments from time to time), but I think it would be worth considering adding the unbiased method of calculating kurtosis if you or users of the package think it would be of any use to them. If that messes up with your algos you use to get these stats quicky, then I understand you don't want to jeoparidze the speed for such a small nitpick.

**Comment by SebKrantz** [comment]
Ok. What I meant there is just this: I can add some corrections following an algorithm without compromizing speed, but I won't start reporting a whole different statistic i.e. I won't start reporting the excess kurtosis because an unbiased measure for that exists instead of the kurtosis. I am thus wondering if taking the unbiased measure of the xcess kurtosis and adding 3 gives an unbiased measure of the kurtosis. Probably not I think.

**Comment by davidbudzynski** [comment]
that makes sense to me! and yeah, adding 3 to the ubiased kurtosis won't get you what you want.

**Comment by SebKrantz** [comment]
This might be a question @harrelfe might be able to answer i.e.: is there an unbiased estimate of the population kurtosis as there is for the [population excess kurtosis](https://en.wikipedia.org/wiki/Kurtosis#Standard_unbiased_estimator)? In that case `collapse::qsu()` should probably adopt it instead of computing Pearson's kurtosis as is `moments::kurtosis()`.

**Comment by davidbudzynski** [comment]
check [this ](https://rdrr.io/rforge/e1071/man/kurtosis.html) doc page. I think it would be type 2 that you would want to use?
