### ISSUE TITLE
many-to-one left/right join

### ISSUE THREAD

**Issue by zander-prinsloo** [SebKrantz/collapse#504]
Hello!

Another comment on `collapse::join()`. For a left join, it does not allow a one-to-many join, nor for a right join does it allow many-to-one. See the latter case illustrated below: a right join where `y` is uniquely identified by the key but `x` is not, enforces a one-to-one join. I expected something like the `merge.data.table()` output below. I also include the function with different `verbose` specifications to illustrate that it's not this parameter driving the one-to-one join. 

Thanks !

``` r
# load packages
library(collapse)
#> Warning: package 'collapse' was built under R version 4.3.2
#> collapse 2.0.6, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
library(data.table)

# Create data.tables where 'id' is not unique for x
x1 = data.table(id = c(1L, 1L, 2L, 3L, NA_integer_),
                t  = c(1L, 2L, 1L, 2L, NA_integer_),
                x  = 11:15)
y1 = data.table(id = c(1,2, 4),
                y  = c(11L, 15L, 16))
# `collapse::join(how = "right")` - enforces 1:1 instead of m:1
collapse::join(
  x   = x1, 
  y   = y1, 
  how = "right", 
  on  = "id", 
  verbose = 0
)
#>    id  t  x  y
#> 1:  1  1 11 11
#> 2:  2  1 13 15
#> 3:  4 NA NA 16
collapse::join(
  x   = x1, 
  y   = y1, 
  how = "right", 
  on  = "id", 
  verbose = 1
)
#> right join: x1[id] 2/5 (40%) <m:m> y1[id] 2/3 (66.7%)
#>    id  t  x  y
#> 1:  1  1 11 11
#> 2:  2  1 13 15
#> 3:  4 NA NA 16

# Expect something like: `merge.data.table()` - allows m:1
merge.data.table(
  x = x1, 
  y = y1, 
  by = "id", 
  all.y = TRUE
)
#>    id  t  x  y
#> 1:  1  1 11 11
#> 2:  1  2 12 11
#> 3:  2  1 13 15
#> 4:  4 NA NA 16

# `collapse::join(how = "right")` allows 1:m
collapse::join(
  x   = y1, 
  y   = x1, 
  how = "right", 
  on  = "id",
)
#> right join: y1[id] 2/3 (66.7%) <m:m> x1[id] 3/5 (60%)
#>    id  y  t  x
#> 1:  1 11  1 11
#> 2:  1 11  2 12
#> 3:  2 15  1 13
#> 4:  3 NA  2 14
#> 5: NA NA NA 15
```

**Comment by SebKrantz** [comment]
Hi, thanks, so in general, `collapse` currently only does 1:1 joins i.e. there is no cartesian-type logic / duplication of records implemented at all. That is presumably one of the reasons why these joins are fast. I am working on adding an argument that will allow all multiple matches that occur and inflate the tables accordingly.

**Comment by zander-prinsloo** [comment]
Hi, thank you that would be super useful! It is super fast which is really great, and I think adding the ability to do multiple matches would be very very useful, at least to do m:1 and 1:m joins. 

I see that there is also an inconsistency the full join in when there is a _many_ key, the output is different depending on whether that table is the left or the right table, which shouldn't be the case. I believe this is due to the same thing that you're describing above, but I'm putting an example below just in case it is useful to you:

``` r
y3 <- data.table::data.table(id = c("c","b", "c", "a"),
                             y  = c(11L, 15L, 18L, 20L))

x3 <- data.table::data.table(id=c("c","b", "d"),
                               v=8:10,
                               foo=c(4,2, 7))

collapse::join(
      x = y3,
      y = x3,
      on = "id",
      how = "full"
    )
#> full join: y3[id] 3/4 (75%) <m:m> x3[id] 2/3 (66.7%)
#>    id  y  v foo
#> 1:  c 11  8   4
#> 2:  b 15  9   2
#> 3:  c 18  8   4
#> 4:  a 20 NA  NA
#> 5:  d NA 10   7
collapse::join(
      x = x3,
      y = y3,
      on = "id",
      how = "full"
)
#> full join: x3[id] 2/3 (66.7%) <m:m> y3[id] 2/4 (50%)
#>    id  v foo  y
#> 1:  c  8   4 11
#> 2:  b  9   2 15
#> 3:  d 10   7 NA
#> 4:  c NA  NA 18
#> 5:  a NA  NA 20
```

**Comment by SebKrantz** [comment]
The full join simply appends records in y not first-matched in x to x. So yes, the order matters and should not be the same because the rows of x are not changed at all in the full join. You can specify sort = TRUE to have the key sorted. I am working on a multi-matching argument that will yield behavior closer to what you are expecting in all of these examples, but also this will be more expensive and not be the default setting.

**Comment by SebKrantz** [comment]
With `multiple = TRUE` passed to `join()` in collapse 2.0.7, these examples also perform as expected.
