### ISSUE TITLE
`frange(x, finite=TRUE)` and `.range(x, finite=TRUE)`

### ISSUE THREAD

**Issue by MLopez-Ibanez** [SebKrantz/collapse#511]
[base::range](https://stat.ethz.ch/R-manual/R-devel/library/base/html/range.html) has an argument `finite` "logical, indicating if all non-finite elements should be omitted."

It would be great if `frange` and `.range` had the same. One could use `replace_inf` to replace the infinities with `NA` but that creates a copy that is typically not needed.

**Comment by SebKrantz** [comment]
Thanks, sure that is not problem, will so it as I find time...
