### ISSUE TITLE
Wrong conditional fsummarize

### ISSUE THREAD

**Issue by GutUrago** [SebKrantz/collapse#513]
Collapse is giving the wrong aggregation, while dplyr is returning the answer that I want. Is my syntax wrong, or why is it giving me the opposite answer? I was working on a large dataset and suspected the aggregation result. Is there any way to do it better since I'm working on many numerical and factor variables at the same time?

``` r

library(collapse)
library(data.table)
library(tidyverse)

test <- data.table(id = c("A", "A", "B", "B", "C", "C"),
                   va = factor(c("Yes", "No", "No","No", "Yes", "Yes"))) 

# Opposite to what I want to get
test %>% fgroup_by(id) %>% 
        fsummarise(va = qF(fifelse(any(va == "Yes"), yes = "Yes", no = "No")))
#>    id  va
#> 1:  A  No
#> 2:  B Yes
#> 3:  C  No

# What I want to get
test %>% group_by(id) %>% 
        summarise(va = qF(fifelse(any(va == "Yes"), yes = "Yes", no = "No")))
#> # A tibble: 3 × 2
#>   id    va   
#>   <chr> <fct>
#> 1 A     Yes  
#> 2 B     No   
#> 3 C     Yes
```

**Comment by SebKrantz** [comment]
Not sure, I figured it all works fine until the step `qF()`. but regardless, this is extremely inefficient code, because you are executing `fifelse()` and `qF()` N.groups times rather than just one time. The more efficient solution would be:

```r
test %>% fgroup_by(id) %>% 
  fsummarise(va = any(va == "Yes")) |> 
  fmutate(va = qF(fifelse(va, yes = "Yes", no = "No")))
```

This gives the same with both dplyr and collapse.

**Comment by SebKrantz** [comment]
Note: I presume this is because collapse internally uses `unlist()` to combine the results from `fsummarise()`, and since you have one-element factors, this may alter things.

**Comment by GutUrago** [comment]
Thank you @SebKrantz  for your quick hint!
