### ISSUE TITLE
collapse::allNA identifies data.frame as list

### ISSUE THREAD

**Issue by Steviey** [SebKrantz/collapse#515]
**_R latest, collapse latest, Ubuntu 20.04.5 LTS_**

```
df <- data.frame(A = c(1, 2, NA, 4), B = c(NA, NA, NA, NA))

result <- collapse::allNA(df)

Gives me: 
Error in collapse::allNA(df) : Unsupported type 'list' passed to allNA()

Actually I want to get a result like:
df <-df %>% dplyr::select_if(~!all(is.na(.)))
```
What can we do here?

**Comment by Steviey** [comment]
Got it with:
test<-collapse::get_vars(df,!collapse::allNA)

**Comment by SebKrantz** [comment]
`allNA()` does not have a data frame method. You can use `all(dapply(df, allNA))`. `collapse::get_vars(df,!collapse::allNA)` should not work because you are not passing a function to it. Use `collapse::get_vars(df, function(x) !collapse::allNA(x))`.

**Comment by Steviey** [comment]
Okay thx, I missinterpreted 'allv(x, value)', assuming uppercase X.
