### ISSUE TITLE
Reuse of GRP-Objects as group_by-substitute

### ISSUE THREAD

**Issue by Steviey** [SebKrantz/collapse#517]
Considering these statements, how can we reuse a GRP-object (globalGroupVar) as group_by-statement? Is this possible?

```
globalGroupVar<<-collapse::qG(df$qRank)

df0 <-df %>% 
  collapse::fgroup_by(c('qRank')) %>%
  collapse::fmutate(cutId=rowid(qRank)) %>%
  collapse::fungroup() %>%
  collapse::fsubset(cutId<=3)


df1 <-df %>% 
	dplyr::group_by(qRank) %>%
	dplyr::slice_tail(.,n=3) %>%
	dplyr::ungroup() 

```

**Comment by SebKrantz** [comment]
Not sure what you are requesting here. But as I said earlier, please write clear and reproducible issues using `reprex::reprex`. If you cannot put the effort to make nicer issues I will not put effort to attend them.

**Comment by Steviey** [comment]
```
df <- tibble(
  col1 = c(1, 2, 3, 4, 5),
  col2 = c("A", "B", "C", "D", "E"),
  qRank = as.factor(c("Low", "Medium", "High", "Low", "Medium"))
)

globalGroupVar<-collapse::qG(df$qRank)

df0 <-df %>% 
  globalGroupVar %>%
  collapse::fmutate(cutId=rowid(qRank)) %>%
  collapse::fungroup()
  
```

**Comment by SebKrantz** [comment]
What is the point of this? You are piping a data frame  into a a vector... a non sensical thing to do. I suggest to either create a grouped data frame using fgroup_by() and use it repeatedly, or directly program operations using grouping objects. See e.g. the Introduction to collapse vignette section on grouping objects and the blog post on programming with collapse.

**Comment by Steviey** [comment]
Thx, I did so, but was not sure if there would be another way.
