### ISSUE TITLE
fsum() gives different result than sum()

### ISSUE THREAD

**Issue by oboysen** [SebKrantz/collapse#540]
I am using the two from within data.table and by accident found out that the results differ slightly.
For example:
sum() returns 620004674.39100003242 while fsum() for the exact same data returns 620004674.3909907341
While the difference is small, it still is puzzling.
In any case, thanks for the great package! I just thought it's worth to note this in case the authors are not aware of this.

**Comment by SebKrantz** [comment]
Thanks, what is the data size that you are computing on? And what is your system? `fsum()` uses a simple double aggregator (which is also the largest type on Apple Silicon Macs), whereas `sum()` may use a long double type on windows.

**Comment by oboysen** [comment]
Thanks for your reaction. The variables are double on a Windows 10 64bit system. I stumbled over this when I calculated check sums, one time with sum() and the other with fsum(), and then compared those later for testing.

**Comment by SebKrantz** [comment]
Yeah, so `sum()` then probably uses a long double on your system. Long double's do however not support SIMD vectorization, so you have a tadeoff here: efficient vectorization with `fsum()` (up to 20x faster than `sum` at least on MAC), or greater numerical accuracy with `sum()`. This is by design.
