### ISSUE TITLE
Cannot install on linux (debian 10)

### ISSUE THREAD

**Issue by eke-arua** [SebKrantz/collapse#556]
Hi,

I've tried everything to install collapse in R on my system. I keep getting the following error message:

In file included from /home/eke/R/x86_64-pc-linux-gnu-library/4.3/RcppEigen/include/Eigen/Core:19,
                 from /home/eke/R/x86_64-pc-linux-gnu-library/4.3/RcppEigen/include/Eigen/Dense:1,
                 from /home/eke/R/x86_64-pc-linux-gnu-library/4.3/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:22,
                 from <command-line>:
/home/eke/R/x86_64-pc-linux-gnu-library/4.3/RcppEigen/include/Eigen/src/Core/util/Macros.h:679:10: fatal error: cmath: No such file or directory
  679 | #include <cmath>
      |          ^~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:191: ExportSymbols.o] Error 1
ERROR: compilation failed for package ‘collapse’

I made sure all dependencies are installed. Not sure what to do next. The collapse package is a dependency for a different package which I am running analysis on. Admittedly, I have not been a linux user for long but I normally sort out installation issue by installing something through the terminal. In this case, I have no idea what that would be.

**Comment by SebKrantz** [comment]
It seems you are missing a basic component of the C programming language, which is the 'cmath' library. Please try installing it.

**Comment by eke-arua** [comment]
Thanks. That worked.

Seems like that

I used this to fix it:

sudo apt-get purge build-essential
sudo apt-get install build-essential
