### ISSUE TITLE
Clarify the distinction between roworder() and roworderv()

### ISSUE THREAD

**Issue by JosiahParry** [SebKrantz/collapse#565]
I want to use a fast function to order a data.frame based on a provided column. Naturally, I am looking towards collapse for that. There appear to be two functions thatI can use. But based on the documentation I am unclear what the difference is between `roworder()` and `roworderv()`
https://github.com/SebKrantz/collapse/blob/a492a76dd738365440ace922fa8592d5907be8ce/man/roworder.Rd#L1-L3

**Comment by JosiahParry** [comment]
It may also be worth noting that this is also not clear in the data.table::setordevr() documentation. Perhaps there is an understanding among users of data.table what the v suffix is but its not clear to myself as a new comer :)

**Comment by SebKrantz** [comment]
Hmm, I thought at least the examples are quite clear. Basically roworder() is an NSE function that you can supply unquoted column names to an a ‚-‚ for descending sort, like data.table::setorder(). roworderv() is the SE equivalent, like data.table::setorderv(), which you can program by supplying colums to sort on to cols and indicating in descending how they should be sorted. There are quite a few functions in collapse the have these two versions, where the „v“ variant fully supports SE programming and the other variant allows NSE or other interactive convenience. 

Perhaps you‘d like to tell me how you‘d like to have the documentation changed?

**Comment by SebKrantz** [comment]
This naming convention is inspired by data.table. As far ad I understand, „v“ might stand for „variables“, suggesting that you can supply a vector of variables the function should operate on.

**Comment by JosiahParry** [comment]
Ah, that helps a lot! 

Perhaps in the details you could have something like: 

`roworder()` is intended to be used with non-standard evaluation whereas the `roworderv()` requires users to pass in a vector of variable names or indices.
