### ISSUE TITLE
Column selecting when using pivot() or across()

### ISSUE THREAD

**Issue by ttrodrigz** [SebKrantz/collapse#586]
This is more of a question, not an issue. I am wondering if there is a collapse equivalent to a tidyselect style of selecting variables within functions such as `pivot()` or `fsummarise(..., across())`.

Here are some things, for example, I do on a very regular basis using dplyr or tidyr:
```
pivot_longer(
    data = iris,
    cols = where(is.numeric)
)

pivot_longer(
    data = iris,
    cols = matches("\\.")
)

summarise(
    iris,
    across(
        .cols = where(is.numeric),
        .fns = fmean
    )
)
```
Is there a way within collapse for variable selecting by a logical condition or via regex? I know that the `gvr()` function allows for selecting of columns by regex, but I don't know if that can be paired with other functions?

Thanks for all the great work, I love the collapse packge.

**Comment by SebKrantz** [comment]
Regex is more difficult, you can only use a compound pipe. The others are easier, you can directly use the selector function:

```r
library(fastverse)

pivot(iris, values = is.numeric)

iris %>% pivot(values = gvr(., "\\.", return = "names"))

fsummarise(
  iris,
  across(
    .cols = is.numeric,
    .fns = fmean
  )
)
```

**Comment by ttrodrigz** [comment]
Understood, thank you! The collapse version of the summarise operation is slick.

**Comment by ttrodrigz** [comment]
Understood, thank you! The collapse version of the summarise operation is slick.
