### ISSUE TITLE
The first data.table in collapse's `join()` can be affected by data.table reference ops on the result

### ISSUE THREAD

**Issue by D3SL** [SebKrantz/collapse#617]
This seems like a fairly standard bug where reference operations affect other tables when they shouldn't, but the catch is it's dependant on mixing collapse and data.table, on the order two tables are joined in, and sometimes on other factors like whether or not you use data.table's "i" clause and what exactly you're doing.

Here's the most minimal example:

1. Start with two data.tables  test1 and test2
3. Join them in this specific order: `collapse::join(test1,test2)`
4. Use data.table to perform a reference option on the post-join table affecting a column that came from test1

```R
test2<-data.table(joincol=1:5,upper=LETTERS[1:5])
test1<-data.table(joincol=1:5, lower=letters[1:5])

#table test1 is first
joined<-join(
  test1,
  test2
)

#the column affected is from test1
joined[,lower:="FOO"]

test1
```

And here's where it gets weird. When using `str_extract()` on the column instead of just reassigning it entirely the bug only occurs if I use the "i" clause to subset the table (`  lower %like% "\\(.+\\)"`)

```R
test2<-data.table(joincol=1:5,upper=LETTERS[1:5])
test1<-data.table(joincol=1:5, lower=letters[1:5])

test2[upper %like% "A|B|C",upper:=paste0(upper,"(",joincol,"-",joincol+1,")")]
test1[lower %like% "a|b|c",lower:=paste0(lower,"(",joincol,"-",joincol+1,")")]

joined<-join(
  test1,
  test2
)

joined[
  lower %like% "\\(.+\\)"
,
  `:=`(
    lower=str_extract(lower,"([aA-zZ])\\(",group=1),
  )
]
test1
```

Whatever this is seems tied to joining with collapse and then performing reference operations using data.table. If you join with `merge()` nothing happens, if you perform reference operations with `settransform()` nothing happens.

**Comment by SebKrantz** [comment]
Thanks, I can look into it, but from the outset this seems to be a data.table issue that whenever you create shallow copy reference operations carry through. 

``` r
library(data.table)
#> Warning: package 'data.table' was built under R version 4.3.1
mtcars <- mtcars
setDT(mtcars)
mtcars_copy <- identity(mtcars)
mtcars_copy[, mpg := 1]
head(mtcars)
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <num> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
#> 1:     1     6   160   110  3.90 2.620 16.46     0     1     4     4
#> 2:     1     6   160   110  3.90 2.875 17.02     0     1     4     4
#> 3:     1     4   108    93  3.85 2.320 18.61     1     1     4     1
#> 4:     1     6   258   110  3.08 3.215 19.44     1     0     3     1
#> 5:     1     8   360   175  3.15 3.440 17.02     0     0     3     2
#> 6:     1     6   225   105  2.76 3.460 20.22     1     0     3     1
```

<sup>Created on 2024-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
library(data.table)
#> Warning: package 'data.table' was built under R version 4.3.1
mtcars <- mtcars
setDT(mtcars)
mtcars_copy <- identity(mtcars)
setDT(as.data.frame(mtcars_copy))
mtcars_copy[, mpg := 1]
head(mtcars)
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <num> <num> <num> <num> <num> <num> <num> <num> <num> <num> <num>
#> 1:     1     6   160   110  3.90 2.620 16.46     0     1     4     4
#> 2:     1     6   160   110  3.90 2.875 17.02     0     1     4     4
#> 3:     1     4   108    93  3.85 2.320 18.61     1     1     4     1
#> 4:     1     6   258   110  3.08 3.215 19.44     1     0     3     1
#> 5:     1     8   360   175  3.15 3.440 17.02     0     0     3     2
#> 6:     1     6   225   105  2.76 3.460 20.22     1     0     3     1
```

<sup>Created on 2024-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
On the `i`-clause issue, my interpretation is as follows: `str_extract` creates a new vector, i.e., a deep copy. So without `i` the frame creates a new reference not affecting the old one. But with `i`, *data.table* just overwrites a part of the original vector with the result, so the modification is present in both frames.

**Comment by D3SL** [comment]
>collapse::settransform does not really modify by reference. It's just a wrapper around ftransform reassigning the result to the parent environment. Docs are a bit misleading here I agree.

Ahhh, gotcha, there's the missing piece in all this. 

> there is nothing I can do to remedy this without deep copying that column.

So I did a quick check and the dataframes themselves do all have unique memory addresses: 

```R
> address(test1)
[1] "000001f4fba2d940"
> address(joined)
[1] "000001f4fd283640"
> address(test1$lower)
[1] "000001f4e6d0ab08"
> address(joined$lower)
[1] "000001f4e6d0ab08"
```

I think the ideal solution in theory is somehow finding out when a column has multiple tables pointing to it. Then you'd know when you need to deep copy. Unfortunately as far as I know that's not possible in R itself. The only thing I could think of was mapping `data.table::address()` across the entire global environment and all columns whenever a dataframe is encountered.

It's quite fast in testing but I have no idea how this would scale with larger environments, or how it would handle cross-environment issues like being called inside a function.

```R
library(purrr)
library(data.table)
library(collapse)

global_addresses2<-map(ls(),\(x){

  if( inherits(get(x),"data.frame")){
    child_addresses<-imap(get(x),\(x,idx){
        address(x)
    })
    output<-c(address(x),child_addresses)
    names(output)<-c(x,paste0(x,"$",names(child_addresses)))
    output
  } 


global_addresses2<-global_addresses2 |> 
  unlist2d(idcols=c("item_group","item_name"),DT=TRUE) |> 
  frename(address=V1) |> 
  ftransform(type=fifelse(item_name %like% "\\$","column","dataframe"))

global_addresses2<-join(
  global_addresses2,
  global_addresses2[type=="dataframe",.(item_group,parent_name=item_name,parent_address=address)]
) |> fsubset(type=="column")

global_addresses2[,refcount:=.N,by="address"]

})
```

**Comment by SebKrantz** [comment]
Thanks, of course one could do very complicates solutions here, but for me the bottom line is that this is not a *collapse* issue and has nothing to do with `join()`, which just doesn't create deep copies unless they are necessary. In general, `:=` just like `collapse::setv`, or `setTRA` etc. just modifies data in-place and it does not check which data.frames or other structures in R are pointing to this data. The data frames have unique memory addresses because they are different. But the data frame is just a list, the data referenced in this list, i.e., the column vectors can be shared scross data frames. This is just how R works. *data.table* was created at a time when R was horribly inefficient and every modification of a data frame entailed a full deep copy of the frame. If you ask me, something like `:=` is not necessary in modern R anymore from an efficiency perspective. Shallow copies as in `settransform()` are just as efficient. Its nice to have, but if you use it you need to understand that you're simply overwriting data in memory and nobody will check if this affects other objects in your environement.
