### ISSUE TITLE
Collapse not matching Cyrillic when read from data, all tests shows equality

### ISSUE THREAD

**Issue by D3SL** [SebKrantz/collapse#618]
I'm working with a few data sets that have Cyrillic strings. While trying to join in translations one kept failing to match. Every single R test I can think of reports perfect equality between the two values. Copying and pasting the string into `ckmatch` or making a new table that way (including dput) fixes the problem. 

Other packages like dplyr and data.table work fine, this one is collapse specific.

I was able to reproduce the issue by saving a sample problem row as an RDS, [attached here](https://github.com/user-attachments/files/16437714/cyrillic.test.row.zip). The bug can be reproduced easily:

```R
library(collapse)

test<-readRDS("attachment.zip")
ckmatch(test,data.frame(regulator_name = "Ростелеком"))
```

**Comment by SebKrantz** [comment]
Thanks, yeah this is indeed a collapse issue which I need to investigate at some point. Currently only seems to work well with UTF8 characters.

**Comment by D3SL** [comment]
Interesting, I thought I was working with UTF-8 cyrillic. If it was silently in some other encoding that could explain why bouncing the dataframe through dput led to `ckmatch` working fine with cyrillic...

**Comment by SebKrantz** [comment]
This issue should now be fixed. Your input file is indeed not UTF8 format, but I now built in checking and conversion to UTF8 routines.
