### ISSUE TITLE
Qualified calls and namespace resolution for `across` and related functions

### ISSUE THREAD

**Issue by alinacherkas** [SebKrantz/collapse#621]
### Describe the bug

Consider a use case where functions from `collapse` are invoked using qualified calls, i.e., `collapse::function`. This is the preferred approach if one writes another package or just wants to keep the environment clean. Now, taking an example from [`across`](https://sebkrantz.github.io/collapse/reference/across.html#ref-examples):

**Scenario 1: Attach the package**

This works:

```r
library(collapse)
fsummarise(wlddev, across(PCGDP:GINI, fmean, w = POP))
#>      PCGDP   LIFEEX     GINI
#> 1 7956.238 65.88068 39.52428
```

**Scenario 2: Qualified calls**

This doesn't work:

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error: 'across' is not an exported object from 'namespace:collapse'
```

**Scenario 3: Qualified calls after exporting across**

Let's modify `NAMESPACE` to add `export(across)` and rebuild `collapse`. This still doesn't work but the error is different:

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error in collapse::across(PCGDP:GINI, collapse::fmean, w = POP) : 
#>  across() can only work inside fmutate() and fsummarise()
```

This is expected because throwing an error is, in fact, [all that `collapse::across` does](https://github.com/SebKrantz/collapse/blob/188b9577c0b933edb5a372c32a33547bb314fee4/R/fsubset_ftransform_fmutate.R#L486-L488). Looking into the definition of `fsummarise`, one can notice that the heavy lifting is actually done by `do_across`, and `across` is just [a call name](https://github.com/SebKrantz/collapse/blob/188b9577c0b933edb5a372c32a33547bb314fee4/R/fsummarise.R#L93-L94). Enter scenario 4.

**Scenario 4: Qualified calls after replacing across with a dummy**

This doesn't work, but the error is now related to `fmean`:

```r
# asign a different function the same name
across <- dplyr::across
collapse::fsummarise(collapse::wlddev, across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error in fmean(.data_, w = POP, drop = FALSE) : 
#>  could not find function "fmean"
```

So slightly modifying the above, one obtains a working solution:

```r
across <- dplyr::across
collapse::fsummarise(collapse::wlddev, across(PCGDP:GINI, collapse::fmean.default, w = POP))
#>      PCGDP   LIFEEX     GINI
#> 1 7956.238 65.88068 39.52428
```

In fact, defining across is not even needed:

```r
# clean the environment
across
#> Error: object 'across' not found
# this still works
collapse::fsummarise(collapse::wlddev, across(PCGDP:GINI, collapse::fmean.default, w = POP))
#>      PCGDP   LIFEEX     GINI
#> 1 7956.238 65.88068 39.52428
```

**Questions**

1. Is this the expected behaviour?

In `dplyr`, for example, you can do both:

```r
dplyr::summarise(collapse::wlddev, across(PCGDP:GINI, ~ weighted.mean(.x, w = POP, na.rm = T)))
#>      PCGDP LIFEEX     GINI
#> 1 7956.238     NA 39.52428
dplyr::summarise(collapse::wlddev, dplyr::across(PCGDP:GINI, ~ weighted.mean(.x, w = POP, na.rm = T)))
#>      PCGDP LIFEEX     GINI
#> 1 7956.238     NA 39.52428
```

This is possible because they check the calling environment in a [different way](https://github.com/tidyverse/dplyr/blob/cdc99196a2d80f14b48ceb5edad328ab34a5bf65/R/across.R#L193-L197).

2. What is the preferred way to perform the above calculation without attaching the package?

While this works:

```r
collapse::fsummarise(collapse::wlddev, across(PCGDP:GINI, collapse::fmean.default, w = POP))
```

Not qualifying `across` seems odd.

3. What is the recommended way to call `fmean` and related functions? As shown above, `collapse::fmean` does not properly resolve.

### Steps/Code to Reproduce

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error: 'across' is not an exported object from 'namespace:collapse'
```

### Expected Results

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#>      PCGDP   LIFEEX     GINI
#> 1 7956.238 65.88068 39.52428
```
### Actual Results

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error: 'across' is not an exported object from 'namespace:collapse'
```

If exported as is:

```r
collapse::fsummarise(collapse::wlddev, collapse::across(PCGDP:GINI, collapse::fmean, w = POP))
#> Error in collapse::across(PCGDP:GINI, collapse::fmean, w = POP) : 
#>  across() can only work inside fmutate() and fsummarise()
```

### Session Info

```r
> sessionInfo()
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.6.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: ...
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.2    parallel_4.3.2    tools_4.3.2       rstudioapi_0.16.0 Rcpp_1.0.13      
[6] collapse_2.0.15   renv_1.0.3 
```

P.S. Thank you for this useful and performant package!

**Comment by SebKrantz** [comment]
Thanks, I'll see what I can do about `fmean`. `across()` is not exported because this would give a namespace conflict with `dplyr`. I had though about calling it `facross()`, but decided against it because it is unnecessary to use qualified names in this case, although I of course understand that this comes as a surprise.

**Comment by SebKrantz** [comment]
This is now fixed.
