### ISSUE TITLE
Inconsistent results with fmutate

### ISSUE THREAD

**Issue by romu545** [SebKrantz/collapse#626]
Greetings.
I have the following problem with fmutate. When using arguments other than "all" for a row-0 dataframe, the function removes the 'names' attribute.
What do you recommend?
I need the names to be preserved both for cases in which records exist and for those in which they do not.
Thanks, I'll be waiting!

Example:
`
# CON COLLAPSE
iris |> 
  fsubset(Petal.Length > 100) |> 
  fmutate("variable" = Species, .keep = "none") |>
  attributes()

# CON DPLYR
iris |> 
  fsubset(Petal.Length > 100) |> 
  mutate("variable" = Species, .keep = "none") |> 
  attributes()
`

**Comment by SebKrantz** [comment]
Thanks. This is a bit difficult to fix the way `fmutate()` is currently constructed, basically the `.keep` argument calls a function which also removes empty/NULL columns. However, you can use function `fcompute()` instead here to get the desired result.

**Comment by romu545** [comment]
Gracias, Ha sido una limitante que algunas de las funciones de collapse generen error con _'Dataframes'_  con cero filas o vacíos.
