### ISSUE TITLE
Typo in Collapse and Data Table vignette

### ISSUE THREAD

**Issue by eeemda** [SebKrantz/collapse#630]
Hi,

Just wanted to note a typo in the collapse and data.table vignette. The line referenced below reads "`data.table` makes data management, and computations on data very easy and salable..."

I think it should read "data.table makes data management, and computations on data very easy and _scalable_..."

https://github.com/SebKrantz/collapse/blob/812eba34a5947095f622cc5c031605e95dd7cadf/vignettes/collapse_and_data.table.Rmd#L43

**Comment by SebKrantz** [comment]
Thanks! Will fix soon.
