### ISSUE TITLE
'group.starts' returns NULL 

### ISSUE THREAD

**Issue by JamesThompsonC** [SebKrantz/collapse#631]
Thank you for the wonderful package.

I think I found a bug:

Returns: NULL, but expected 1
```
d <- data.frame(x = 1, y = 1)
g <- collapse::GRP(d, "y")
g$group.starts

d <- data.frame(x = 1:2, y = 1:2)
g <- collapse::GRP(d, "y")
g$group.starts
```
This works as expected
```
d <- data.frame(x = 1:2, y = 1)
g <- collapse::GRP(d, "y")
g$group.starts

```

~Jim

**Comment by SebKrantz** [comment]
Thanks. I have fixed this. Basically, the current code said that if there is only one group or the number of groups is equal to the number of observations, the group.starts attribute is redundant. However, I understand that this is somewhat inconsistent and somewhat undocumented.
