### ISSUE TITLE
Fast Functions slower than Base R?

### ISSUE THREAD

**Issue by docfleetwood** [SebKrantz/collapse#634]
Is it expected behavior that fsum is 3-5 times slower than the base R sum function? The same is true for the fmean function. This is true regardless of the na.rm setting in the fast functions or base functions. Are the fast functions 'only' faster if one is using them while grouping? And even so, why would they be ~4 times slower for simple use cases? I assumed I could just replace the base functions with the fast functions and at least be as fast, but mostly faster.

or...

Is there something weird going on with my machine and they should not be slower?

Simple example:

microbenchmark::microbenchmark(
  base = sum(iris$Sepal.Length),
  fast_fun = fsum(iris$Sepal.Length),
  unit = 'relative'
)

Example of my output:

Unit: nanoseconds
     expr  min   lq mean median   uq   max neval
     base  600  700 1041    700  800 22400   100
 fast_fun 3500 3700 4334   3900 4000 45500   100

**Comment by SebKrantz** [comment]
Hi, so for a modeately sized vector I get

``` r
library(collapse)
#> Warning: package 'collapse' was built under R version 4.3.3
#> collapse 2.0.16, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
x = rnorm(1e6)
microbenchmark::microbenchmark(
  base = sum(x),
  fast_fun = fsum(x),
  fast_fun_nona = fsum(x, na.rm = FALSE),
  unit = 'relative'
)
#> Warning in microbenchmark::microbenchmark(base = sum(x), fast_fun = fsum(x), :
#> less accurate nanosecond times to avoid potential integer overflows
#> Unit: relative
#>           expr      min       lq     mean   median       uq      max neval
#>           base 1.669197 1.672519 1.670331 1.671089 1.672899 1.657641   100
#>       fast_fun 1.003241 1.003880 1.010811 1.003692 1.003342 1.570585   100
#>  fast_fun_nona 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000   100
```

<sup>Created on 2024-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And, when compiling collapse with OpenMP my M1 Mac, which enables SIMD vectorization, I get

``` r
library(collapse)
#> collapse 2.0.16, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
x = rnorm(1e6)
microbenchmark::microbenchmark(
  base_nona = sum(x),
  base = sum(x, na.rm = TRUE),
  fast_fun_nona = fsum(x),
  fast_fun = fsum(x, na.rm = FALSE),
  unit = 'relative'
)
#> Warning in microbenchmark::microbenchmark(base_nona = sum(x), base = sum(x, :
#> less accurate nanosecond times to avoid potential integer overflows
#> Unit: relative
#>           expr       min        lq      mean    median        uq       max
#>      base_nona 12.156159 12.084536 11.598602 12.027920 11.870942 3.3663102
#>           base 12.151309 12.083574 11.622238 12.028877 11.897287 3.3826872
#>  fast_fun_nona  1.578726  1.573468  1.530402  1.576739  1.569704 0.4557988
#>       fast_fun  1.000000  1.000000  1.000000  1.000000  1.000000 1.0000000
#>  neval
#>    100
#>    100
#>    100
#>    100
```

<sup>Created on 2024-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So yes, fast functions are faster also for non-grouped operations. However, apart from SIMD, the difference it not big. The main speed gains come from grouped operations.

**Comment by SebKrantz** [comment]
The difference on small data may be explained by method dispatch. `fsum()` is S3 generic, `sum()` is primitive.

**Comment by docfleetwood** [comment]
I concur on the medium to large datasets. I was taking the max of just two numbers, but repeating it one million times, when I noticed a pretty extreme difference between max and fmax. (fmax being much, much slower) But that is just because it was only two numbers, and the function was being called repeatedly. Thanks for the response. Collapse is one of my favorite packages.
