### ISSUE TITLE
Sequence along groups

### ISSUE THREAD

**Issue by fschoner** [SebKrantz/collapse#644]
Hi Sebastian,

thanks so much for providing collapse. I found myself re-writing lots of my old data.table code to enhance its performance. One command I use quite often is `df[, by = .(user_id, first_scrape), nof_scrape := sequence(.N)]`, which counts along distinct values of first_scrape within user_id starting from 1. However, it is painfully slow on the dataset I'm currently working with (~170 mio rows) What is the most efficient way I can do this using collapse? Is there a way I can avoid the sequence() function?

Thanks!

**Comment by SebKrantz** [comment]
Hi @fschoner. Thanks! A reprex would have been better. However, I think this can be done more efficiently with `data.table::rowid()`, e.g. `df[, nof_scrape := rowid(user_id, first_scrape)]`. Because of the convenience of `rowid()`, there is no *collapse* function to do the same thing.

**Comment by fschoner** [comment]
Thanks so much, `data.table::rowid()` does the trick!
