### ISSUE TITLE
Switch to `message` instead of `cat` in a few remaining places

### ISSUE THREAD

**Issue by D3SL** [SebKrantz/collapse#649]
Some messaging is still performed using `cat()` instead of `message()`. I don't think there are any warnings output this way so this is really trivial. I _think_ this can be a ctrl+f drop-in replacement.

**Comment by SebKrantz** [comment]
You mean in `join()`? Yes, this is intentional. I want white text to be clearly printed, you can use the `verbose` argument to suppress it.
