### ISSUE TITLE
Idea: qsu() should return weighted counts as N

### ISSUE THREAD

**Issue by mayer79** [SebKrantz/collapse#650]
{collapse} offers a `w` argument in all relevant functions, which is super handy in many situations. 

Could we have `qsu(, w = ...)` return sum(w) in case of non-NULL w?

**Comment by SebKrantz** [comment]
Thanks! I like the idea. Let me see what can be done.

**Comment by SebKrantz** [comment]
The qsu() version with 'WeightSum' column is now in the main branch. Should be available via R-universe within one hour. This was a good idea, gives extra information at no additional computational cost.

**Comment by mayer79** [comment]
A!wesome, thanks a lot!
