### ISSUE TITLE
Soporte en collapg

### ISSUE THREAD

**Issue by romu545** [SebKrantz/collapse#658]
Do the functions in the list of functions passed in the 'custom' parameter have to be in the global environment?

If not, how can I avoid the following error being generated?

```
Error en get(as.character(FUN), mode = "function", envir = envir): 
  el objeto 'foo_1' de modo 'function' no fue encontrado
```
![Captura de pantalla 2024-10-30 131346](https://github.com/user-attachments/assets/53309b91-05f4-4a8e-9b09-5456cc93ff2f)

**Comment by SebKrantz** [comment]
Thanks! I'll investigate it. However, this code is not very efficient. Here is an efficient alternative:

```r
obs_fp_poliproducciones <- function(datos_fp, reg = 4443L) {
  
  rev_poliproduccion <- datos_fp |>
    fsubset(.policultivo != 0,
        registro,
        subregistro,
        tipofasecultivo,
        especie,
        policultivo,
        tipoinfraestructura,
        numeroinfraestructuras,
        areadestinada,
        tecnologiacultivo) |>
    roworder(registro, tipofasecultivo, subregistro) |>
    fgroup_by(registro, tipofasecultivo, policultivo) |>
    fsummarise(subregistro = str_flatten_comma(subregistro, last = 2),
                        especie = fndistinct(especie) > 1,
                        policultivo = fnobs(policultivo) == 1,
                        across(6:9, fndistinct)) |>
    ftransformv(-(1:6), `>`, 1) |>
    pivot(values = 5:10) |> 
    fsubset(value)
}

```

By writing the functions out, you allow *collapse* to optimize them. If you wrap them into functions the way you do, they will not be optimized (*collapse* does not analyze black-box functions to see if they contain vectorized fast statistical functions).

**Comment by romu545** [comment]
Muchas gracias!!!
Me siento muy agradecido por tu ayuda. Me has ayudado a entender como usar de mejor manera las funciones de collapse.
👍🏾
