### ISSUE TITLE
Idea: Can we have a nmax argument in fnunique()?

### ISSUE THREAD

**Issue by mayer79** [SebKrantz/collapse#662]
Thanks a lot for the fantastic package.

One idea: What do you think about an `nmax = NULL` argument in `fnunique()`? As soon as the counter reaches `nmax`, it will stop and return `nmax`. **Edit:** I fear that fnunique() needs to sort the vector anyway, so this won't do the trick... Still I'd be interested in your opinion if there is a shortcut for below example.

A use case: Let's calculate mean(y) by x. But unfortunately, we don't know if we need to bin x first. The two slowest parts in the following code are `fnunique(x)`, followed by `findInterval()`. The first bottleneck could be easily handled via `fnunique(x, nmax=5L)`. `findInterval()` uses bisection in C (https://github.com/wch/r-source/blob/ecca86a2e0209376da57254b7d107cb6f47bec14/src/appl/interv.c) and might be more tricky to speed up.

```r
library(collapse)

n <- 1e6
y <- rnorm(n)
x <- runif(n)
                                                                     # n=1e7   n=1e6
if (is.numeric(x) && fnunique(x) >= 5) {                             # 500ms   34ms
  breaks <- pretty(frange(x), n = 10)                                # 17ms     2ms  
  g <- findInterval(x, vec = breaks, rightmost.closed = TRUE)        # 226ms   23ms  
  g <- qF(g)                                                         # 50ms     5ms (without assigning)
} 
fmean(y, g = g)                                                      # 65ms     6ms
```

**Comment by SebKrantz** [comment]
Thanks. In principle a good idea, however practically difficult because I'd have to modify two internal algorithms used for different purposes. `fnunique()` is currently a wrapper around `fndistinct()` and `group()`:
```r
> fnunique
function (x) 
{
    if (is.list(x) && length(unclass(x)) == 1L) 
        x <- .subset2(x, 1L)
    if (is.atomic(x) && !is.complex(x)) 
        .Call(C_fndistinct, x, NULL, FALSE, 1L)
    else attr(.Call(C_group, x, FALSE, FALSE), "N.groups")
}
```
So in the short term I think this will not happen.

**Comment by mayer79** [comment]
I have solved it for now by a two-step procedure:

```
#' Check if Vector is Numeric
#'
#' Internal function used to check if a variable is numeric *and* has more than
#' m disjoint values. The function shines for extremely long vectors (~1e7).
#'
#' @noRd
#' @keywords internal
#'
#' @param x A vector or factor.
#' @param m How many disjoint values will return FALSE?
#' @returns `TRUE` if x is numeric with > m disjoint values, and `FALSE` otherwise.
is_continuous <- function(x, m = 5L) {
  M <- 10000L
  if (!is.numeric(x)) {
    return(FALSE)
  }
  if (m >= M) {
    stop("Too large value for m")
  }
  if (length(x) <= M) {
    return(collapse::fnunique(x) > m)
  }
  if (collapse::fnunique(x[1L:M]) > m) {
    return(TRUE)
  }
  return(collapse::fnunique(x) > m)
}
```
