### ISSUE TITLE
Fast collapse equivalent of `base::ave()`

### ISSUE THREAD

**Issue by grantmcdermott** [SebKrantz/collapse#665]
Hey Sebastian,

Apologies if I'm missing something obvious, but is there a `collapse` equivalent of `base::ave()` that (a) returns a group-transformed object of the **same length** as the original input and (b) does **not** require a data.frame? 

I can think of functions that meet requirements (a) or (b) separately (e.g., `ftransform` and `fmean`, respectively). But not something that meets both at the same time.

I'm basically looking for a faster version of:

```r
# Hypothetical vectors
a = ChickWeight$weight
b = ChickWeight$Time

ave(a, b, FUN = mean)
ave(a, b, FUN = median)
# etc
```

Thanks!

**Comment by grantmcdermott** [comment]
Perfect, thanks.

FWIW my interest here was motivated by a new feature that I'm contemplating for `tinyplot`, which would allow users to pass arbitrary functions for summarizing data and visualizing the result (similar to `ggplot2::stat_summary()`). We would default to `base::ave`, but it would be cool to enable support for faster equivalents like those provided by `collapse` if the user wants.

Veering slightly off topic, but on a related note:

1. If a user loads` collapse` and sets `set_collapse(mask = "all")`, that would carry over to packages that invoke the masked base operations too, right? (I mean, assuming they don't explicitly invoke the namespace assignment, e.g. `base::unique`). With `tinyplot`, we make use of various manipulation and helper functions like `unique`, `order`, `split` & co. So I'm wondering if users would get an automatic speed bump for plotting large data objects by loading collapse and turning on the masking options?
2. Cool anecdote for you: Earlier this week a colleague reached out to me b/c their simulation code (which was all dplyr-based) was very slow, running at over 30 minutes. I didn't have time to troubleshoot I so simply suggested loading `collapse` and setting `set_collapse(mask = "manip", nthreads = parallel::detectCores()/2)`. This simple two line change led to >10x speed increase and their simulation now completes in around 2 minutes :-)

**Comment by SebKrantz** [comment]
Hi Grant, I believe package code is shielded from other packages namespaces, so it would not be automatically optimized. Functions defined in the global environment however will be optimized. One thing to watch out for is that `set_collapse(mask = ...)` if called in a package will also affect how *collapse* behaves in the global environment, and should thus never be used in packages. 

And thanks for the annecdote, always happy to hear that *collapse* is useful!

**Comment by grantmcdermott** [comment]
> And thanks for the annecdote, always happy to hear that _collapse_ is useful!

Happy to share and thanks again for all the work on this fantastic package!
