### ISSUE TITLE
R Check NOTE: no visible global funciton definition for 'across'

### ISSUE THREAD

**Issue by James-G-Hill** [SebKrantz/collapse#670]
Hello,

Creating a `golem` app and using the `collapse` package, we have used the `across` expression in the `fsummarise` function; this leads to the following `NOTE` when running Check

```
no visible global function definition for 'across'
  Undefined global functions or variables:
    across
```

Is there any way to pass the check?

**Comment by SebKrantz** [comment]
Hi, see here: https://www.r-bloggers.com/2019/08/no-visible-binding-for-global-variable/ and `?globalVariables`. From the docs: 

```r
## assume your package has some code that assigns ".obj1" and ".obj2"
## but not in a way that codetools can find.
## In the same source file (to remind you that you did it) add:
if(getRversion() >= "2.15.1")  utils::globalVariables(c(".obj1", "obj2"))
```

**Comment by James-G-Hill** [comment]
Thanks, that works, although it would be somewhat neater when writing large packages if we could import the function with package name to be consistent; maybe with `collapse::acr` to avoid the clashing import with `dplyr::across`.

**Comment by SebKrantz** [comment]
Regarding your request: The thing is `across()` is not even a function in *collapse*, it is a keyword to do something very different under the hood. And I don't see the point of exporting it.

**Comment by James-G-Hill** [comment]
Cool, I understand; I will just give you the reasons why it would be useful for me so you will understand the reason for my request. I'm not attempting to change your mind.

Context: I work in teams writing production R code and teams can have mixed levels of ability; including newer staff who maybe only ever wrote some basic scripts previously.

Firstly, I want to minimize the number of Notes etc. in Check to the absolute minimum so that there's less to explain to people when teaching them how to use Check. When Check is run the list of issues is also only then showing actually important things and not mixing with known issues to be avoided.

Secondly, putting `utils::globalVariables` works but in a large package / shiny application, then where to put it? It's easily forgotten  about and of course, it's another thing to explain to people. If you forget where you put it then there's a risk of using it in multiple places.

Assigning `NULL` nearby in the code works; but again it's just another thing to explain to newer staff members.

The best way to overcome these issues in my experience is to ensure every function other than those called with `base` use the format `package::function`; no need to worry about remember `@importFrom` in every function Roxygen2 header and it's absolutely clear what package is being used everywhere. As long as those packages are recorded in `Imports` in the `DESCRIPTION` file there are no problems. Combine this with `.data` in Tidyverse functions to refer to column names and the `Undefined global functions or variables` never appears.

**Comment by SebKrantz** [comment]
Understood and of course agree - a couple of people have had this issue. However, I have chosen to call the function `across()` instead of `facross()`. This decision cannot be reverted.

**Comment by James-G-Hill** [comment]
Yeah, I think the best solution probably is just to use `utils::globalVariables` multiple times (if necessary), once at the top of every file where it's needed.

**Comment by SebKrantz** [comment]
TBH I mostly use `object <- NULL` directly in the function, makes it very clear. Anyway, sorry, but I'm closing this now.
