### ISSUE TITLE
fmatch not matching with base match

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#675]
Hi, I wanted to highlight that `fmatch()` is not aligning with `match()` when matching `NA` values. This is having an undesired effect on one of my functions when trying to add `NA` as an explicit level. 

Please see the below reprex.

``` r
library(collapse)
packageVersion("collapse")
#> [1] '2.0.18'
f1 <- factor(NA)
f2 <- factor(NA, exclude = NULL)

unclass(f1); levels(f1)
#> [1] NA
#> attr(,"levels")
#> character(0)
#> character(0)
unclass(f2); levels(f2)
#> [1] 1
#> attr(,"levels")
#> [1] NA
#> [1] NA

fmatch(f1, NA)
#> [1] NA
fmatch(f2, NA)
#> [1] 1

# Base match finds a match no matter the scenario

match(f1, NA)
#> [1] 1
match(f2, NA)
#> [1] 1
```

I also noted the behaviour changed at some point between 2.0.9 and 2.0.18 where `fmatch(f1, NA)` would return 1 and `fmatch(f2, NA)` would return `NA` unless `NA` was `NA_character_`

**Comment by SebKrantz** [comment]
Thanks! This is indeed a case I didn't consider. There is currently a neat shorthand of just matching the levels: 

```c
if(tx == INTSXP-1) { // For factors there is a shorthand: just match the levels against table...
  SEXP nmvint = PROTECT(ScalarInteger(nmv)); ++nprotect;
  PROTECT(table = match_single(getAttrib(x, R_LevelsSymbol), table, nmvint)); ++nprotect;
  int *pans = INTEGER(ans), *pt = INTEGER(table)-1, *px = INTEGER(x);
  if(inherits(x, "na.included")) {
    #pragma omp simd
    for(int i = 0; i < n; ++i) pans[i] = pt[px[i]];
  } else {
    #pragma omp simd
    for(int i = 0; i < n; ++i) pans[i] = px[i] == NA_INTEGER ? nmv : pt[px[i]];
  }
  UNPROTECT(nprotect);
  return ans;
}
```

I guess the second loop needs to be adjusted to use the index of the first `NA` value in `table` instead of `nmv` if `table` has any `NA`'s. Let me think...
