### ISSUE TITLE
unlist2d returns error if empty list is present

### ISSUE THREAD

**Issue by FrancyJGLisboa** [SebKrantz/collapse#99]
Hi. Nice work!

Was playing with collapse using internal data. 
When I have a nested list with 3 levels and one of the levels is empty, the unlist2d function returns "Error in .subset2(l, 1L) : subscript out of bounds".

Is there a way to filter out empty list or nulls before building the data.frame in unlist2d?

Thanks

**Comment by SebKrantz** [comment]
Hi, thanks for flagging this. You can try calling reg_elem() before unlist2d. If you give me a reproducible example I can also further look into this.

**Comment by tpWalker888** [comment]
Hi,
Your programs are proving to be enormously helpful for my work.
I can provide at least 2 files that demonstrate this issue.  They both have public financial information for 2 companies so there would be no privacy issue.
Just let me know,
Thanks

**Comment by SebKrantz** [comment]
Hi, thank you, but I meant like a mock list created in R. I think I know
what the issue is though. I did however not focus on it because calling
reg_elem() on the list beforehand simply solves the problem.
